### PR TITLE
Enable parallel installation of release and debug builds

### PR DESCRIPTION
**Pull request by dmo60**
Hi! Thank you for this great app! 

I wanted to play around with the code and ultimately investigating if I could contribute to the Autofill implementation from #411. But the first thing I noticed is that it's currently not easily possible to have both a release and a debug build installed at the same time. 

This PR addresses this by specifying an `applicationIdSuffix` for the `debug` build type. With that, the debug build will have a different application id (`com.zeapo.pwdstore.debug`) and thus will not collide with the release app when installed on the same device.

This would allow for a "dev"/"testing" environment, where one could e.g. setup a different password store for development purposes. At the same time, the release build would still be available for day-to-day usage.

What one would probably want in this case is a different icon for the debug app to visually differentiate between the two apps in the application launcher. This is where I would need some help, since I neither have any skills in manipulating Vector images, nor do I have access to the source SVG file that was used to generate the launcher icons (it would be nice if this svg source could be added to the repository). Usually a simple "DEBUG" text badge would do the job.

### CODE REVIEW

**Comment by zeapo** [comment]
Nice :)

Thanks for the PR

**Comment by zidhuss** [comment]
Hey @dmo60, could we possibly change the background colour for the debug release?

https://github.com/zeapo/Android-Password-Store/blob/master/app/src/main/res/values/colors.xml#L18

**Comment by zeapo** [comment]
@zidhuss oh sorry, you're right. I didn't think about that. The PR is merged, can you make the change to color you like?

**Comment by dmo60** [comment]
> Hey @dmo60, could we possibly change the background colour for the debug release?

Yep, that's what I actually had in mind as well. I will create a PR for that. Still I think it would be nice if we would indicate the "Debug" in the icon itself as well.

**Comment by dmo60** [comment]
see #472

**Pull request merged**
