### PR TITLE
Rework settings to use ModernAndroidPreferences

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## :scroll: Description
Migrates our existing `UserPreference` code to a dynamically generated preference screen backed by [ModernAndroidPreference](https://github.com/Maxr1998/ModernAndroidPreferences).

~~Blocked on https://github.com/Maxr1998/ModernAndroidPreferences/issues/4~~

## :bulb: Motivation and Context
This allows us to eliminate a lot of boilerplate w.r.t. `findPreference` and `setOnPreferenceClickListener` and focus on getting the real things done. It is also backed by RecyclerView so it's slightly more performant than regular preferences.

## :green_heart: How did you test it?
Verified all previous interactions work as before

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :camera_flash: Screenshots / GIFs

<details><summary>Screenshots of new settings screen</summary>

screenshot-20210110-182235
screenshot-20210110-182238
screenshot-20210110-182242
screenshot-20210110-182245
screenshot-20210110-182249
screenshot-20210110-182252

</details>

### CODE REVIEW

**Comment by msfjarvis** [comment]
I can implement the missing bit myself but I'll just mark this as blocked for now and if I'm done with everything else before Max has had a chance to take a stab at fixing the issue, I'll send a PR.

**Comment by msfjarvis** [comment]
I pushed out my mavenLocal config and everything because I wanted this backed up, the next beta of ModernAndroidPreferences will eliminate the need for a custom build.

**Comment by msfjarvis** [comment]
This should *finally* be ready.

**Comment by msfjarvis** [comment]
One final concern with this is that the list preference's items are a tad _too_ far apart for my liking, but it's relatively low priority and I'll fix it in the backing library soon enough.

<details>
<summary>Screenshot</summary>

screenshot-20210110-182945


</details>

**Comment by msfjarvis** [comment]
`SshKeyImportActivity` didn't correctly finish under some circumstances, fixed it now.

**Review by fmeum — DISMISSED** [review]
Looks really good to me based on code and screenshots, but I haven't been able to try it out yet.

**Comment by msfjarvis** [comment]
> Looks really good to me based on code and screenshots, but I haven't been able to try it out yet.

Thanks! I'm in favour of letting this sit until you've had a chance to take it for a spin, there's a lot of interactions to test and it's pretty likely I missed something that someone else might catch.

**Comment by fmeum** [comment]
I found this to work pretty well, only had to add one more call to `finish()` in `SshKeyImportActivity`.

**Review by fmeum — APPROVED** [review]

**Comment by Maxr1998** [comment]
> One final concern with this is that the list preference's items are a tad _too_ far apart for my liking, but it's relatively low priority and I'll fix it in the backing library soon enough.

[Fixed](https://github.com/Maxr1998/ModernAndroidPreferences/releases/tag/2.2.1) :wink:

**Pull request merged**
