### PR TITLE
Fix two SMS Autofill crashes

### PR DESCRIPTION
**Pull request by fmeum**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description

SMS OTP Autofill currently crashes for two reasons:

1.  Tasks.await has a precondition of not running on the UI thread.
2.  Exceptions thrown from Tasks are always wrapped into
    ExecutionExceptions and need to be unwrapped before they can be
    identified as ResolvableApiException.

This commit addresses both issues by making waitForSms a proper
coroutine using withContext and a custom wrapper around Task<T> that
relies on suspendCoroutine and automatically unwraps exceptions.

## :bulb: Motivation and Context

Turns out the switch over to `lifecycleScope` broke this, but at least now its in a much more dependable state.

## :green_heart: How did you test it?
It works in both the native Twitter app and the PWA and correctly asked for permission on first use.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by fmeum** [comment]
Not sure whether this is worth a second point release given that it is a relatively niche feature, but it seems fully broken in 1.10.1. What do you think @msfjarvis?

**Comment by msfjarvis** [comment]
> Not sure whether this is worth a second point release given that it is a relatively niche feature, but it seems fully broken in 1.10.1. What do you think @msfjarvis?

I think we should do a patch release, then we can also ship out #969 and #982.

**Comment by fmeum** [comment]
> > Not sure whether this is worth a second point release given that it is a relatively niche feature, but it seems fully broken in 1.10.1. What do you think @msfjarvis?
> 
> I think we should do a patch release, then we can also ship out #969 and #982.

Sounds good. Could you also test the SMS Autofill feature in that case, e.g. with Twitter? Just want to make sure this doesn't crash for other reasons.

**Comment by fmeum** [comment]
We should probably also include #984.

**Comment by msfjarvis** [comment]
> > > Not sure whether this is worth a second point release given that it is a relatively niche feature, but it seems fully broken in 1.10.1. What do you think @msfjarvis?
> > 
> > 
> > I think we should do a patch release, then we can also ship out #969 and #982.
> 
> Sounds good. Could you also test the SMS Autofill feature in that case, e.g. with Twitter? Just want to make sure this doesn't crash for other reasons.

Sure.

> We should probably also include #984.

Yeah we can do that.

**Review by msfjarvis — APPROVED** [review]

**Comment by msfjarvis** [comment]
Just confirmed this works for me on Twitter :+1:

**Comment by msfjarvis** [comment]
29 freeRelease seems to be on a really slow runner, 12 minutes for unit tests is just...yikes.

**Pull request merged**
