### PR TITLE
Support multiple authentication methods

### LINKED ISSUE #333: SSH Git sync fails: Auth fail [preauth]
Synchronizing, pulling and pushing have failed for me for the last couple of versions. Whenever I try to do any of these I get the error message shown in the screenshot below.
The relevant output from the server log file `/var/log/auth.log` is the following:
```
Aug  9 15:26:38 raspberrypi sshd[20888]: error: Received disconnect from xxx.xxx.xxx.xxx: 3: com.jcraft.jsch.JSchException: Auth fail [preauth]
```
where `xxx.xxx.xxx.xxx` is my IP.

The server has the correct public keys in the `authorized_keys` file and synchronizing works as expected on my computer. It is only my Android devices that fail. I'm currently using version 1.2.0.68.

Any ideas what might be wrong?

git

### LINKED ISSUE #548: Support multiple authentication methods
Hello,

I configured my SSH server to expect multiple authentication methods:

```
AuthenticationMethods publickey,password
```

When I select "ssh-key" as the method the git pull fails with the following error:

When I select username/password as method the authentication just fails:

- jgit Docu: https://www.codeaffine.com/2014/12/09/jgit-authentication/
- Authentication code in Password-Store: https://github.com/zeapo/Android-Password-Store/blob/f05c0b37ca0df5cab4906d5484572d0288c479ed/app/src/main/java/com/zeapo/pwdstore/git/GitOperation.kt#L51

### LINKED ISSUE #782: [BUG] Can't sync on server with ssh
**Describe the bug**
My remote server uses publickey and password for ssh authentication (it was using OTP as well, but since it looks like this project does not support it, I've disabled it for my passtore user). When I try to sync  my password store I get this message:

```
An error occurred during a Git operation
Error occurred during the sync operation,
Please check the FAQ for possible reasons why this error might occur.Message from jgit:
Attempt to get length of null array
Caused by:
null
```

**To Reproduce**
1. Setup server to use public key and password for ssh auth
2. Add server info on git server settings (I can't choose both SSH key and password, so I marked SSH key)
3. Try to sync the repo

**Expected behavior**
Sync passwords

**Device information (please complete the following information):**
 - Device: Motorola G5
 - OS: 8.1.0
 - App version: 1.7.2

### PR DESCRIPTION
**Pull request by fmeum**
:loudspeaker: Type of change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [x] Refactoring

## :scroll: Description

Add support for multiple authentication methods by offering password authentication after public key authentication.

Along the way, refactor GitOperation to use a (somewhat) proper builder
pattern. This uncovered that we were previously not using SSHJ for the
case of no authentication, which is now rectified.

## :bulb: Motivation and Context

Fixes #333, fixes #548 and fixes #782 if it works.

## :green_heart: How did you test it?
I lack the setup to test this properly and only verified that SSH public key authentication by itself still works as expected. Password authentication, public key followed by password authentication and no authentication still need testing.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code

### CODE REVIEW

**Comment by msfjarvis** [comment]
I can't get this to work for me. After setting `AuthenticationMethods publickey,password` in my sshd_config, trying to clone my repository with the SSH Key connection mode fails here

https://github.com/android-password-store/Android-Password-Store/pull/825/files#diff-efe0564ca4779571d8e3340b0d88a26dR43

**Comment by FabianHenneke** [comment]
> I can't get this to work for me. After setting `AuthenticationMethods publickey,password` in my sshd_config, trying to clone my repository with the SSH Key connection mode fails here
> 
> ~https://github.com/android-password-store/Android-Password-Store/pull/825/files#diff-efe0564ca4779571d8e3340b0d88a26dR43~ Ugh, didn't work. GitOperation.kt, line 43.

Sorry, that `require` shouldn't have made it in in that form: #826.

**Comment by msfjarvis** [comment]
Doesn't throw anymore but still doesn't seem to work, tried both my SSH key as well as password and SSHJ always fails saying all authentication methods were exhausted. I'll try to debug some more on my end...

**Comment by msfjarvis** [comment]
uhh

**Comment by msfjarvis** [comment]
@FabianHenneke can you rebase this and #807 when you get a chance? I have the weekend off so I'm going to try and create a docker setup to allow me to test this.

**Comment by FabianHenneke** [comment]
> @FabianHenneke can you rebase this and #807 when you get a chance? I have the weekend off so I'm going to try and create a docker setup to allow me to test this.

Done, but EDCSA keys remain broken for now. Everything else should work as before.

**Comment by msfjarvis** [comment]
@FabianHenneke would you be able to rebase this some time over the next week? Should leave us enough time to be able to review and test this before the September release.

**Comment by fmeum** [comment]
> @FabianHenneke would you be able to rebase this some time over the next week? Should leave us enough time to be able to review and test this before the September release.

Please review and merge #1084 first.
We are currently offering password authentication implicitly after publickey authentication in both possible cases: As a follow-up authentication mode when publickey auth succeeded and as an alternative authentication mode when it failed. I don't think there is an easy way to differntiate between the two without delving into SSHJ internals, so we should first agree on whether this behavior is okay or not.

**Comment by msfjarvis** [comment]
> > @FabianHenneke would you be able to rebase this some time over the next week? Should leave us enough time to be able to review and test this before the September release.
> 
> Please review and merge #1084 first.
> We are currently offering password authentication implicitly after publickey authentication in both possible cases: As a follow-up authentication mode when publickey auth succeeded and as an alternative authentication mode when it failed. I don't think there is an easy way to differntiate between the two without delving into SSHJ internals, so we should first agree on whether this behavior is okay or not.

I think it's acceptable. I assume we'd only be offering password authentication for servers that do advertise `password` or `keyboard-interactive` authentication methods alongside `publickey`?

**Comment by fmeum** [comment]
> > > @FabianHenneke would you be able to rebase this some time over the next week? Should leave us enough time to be able to review and test this before the September release.
> > 
> > 
> > Please review and merge #1084 first.
> > We are currently offering password authentication implicitly after publickey authentication in both possible cases: As a follow-up authentication mode when publickey auth succeeded and as an alternative authentication mode when it failed. I don't think there is an easy way to differntiate between the two without delving into SSHJ internals, so we should first agree on whether this behavior is okay or not.
> 
> I think it's acceptable. I assume we'd only be offering password authentication for servers that do advertise `password` or `keyboard-interactive` authentication methods alongside `publickey`?

That should be true based on my understanding of the SSHJ code, but I don't have the setup to test it properly.

**Comment by fmeum** [comment]
Maybe we should rethink our AuthMode switches though. If we could make the switches shown depend on whether or not the URL starts with `http://` or `https://`, we could show either a choice between "Password" and "None" (HTTP) or "Public key", "Public key (via OpenKeychain)" or "Password only" (SSH).

**Comment by msfjarvis** [comment]
> Maybe we should rethink our AuthMode switches though. If we could make the switches shown depend on whether or not the URL starts with `http://` or `https://`, we could show either a choice between "Password" and "None" (HTTP) or "Public key", "Public key (via OpenKeychain)" or "Password only" (SSH).

Should certainly not be _impossible_, I can take a stab at it. Do you want it to go in with this PR?

**Comment by fmeum** [comment]
> > Maybe we should rethink our AuthMode switches though. If we could make the switches shown depend on whether or not the URL starts with `http://` or `https://`, we could show either a choice between "Password" and "None" (HTTP) or "Public key", "Public key (via OpenKeychain)" or "Password only" (SSH).
> 
> Should certainly not be _impossible_, I can take a stab at it. Do you want it to go in with this PR?

I would prefer to have this go in as is. The other change would be almost purely UI-related while this does not touch the UI at all, so I would prefer them to remain separate.

**Comment by msfjarvis** [comment]
I tried cloning from a server which only had password authentication after setting authentication mode to SSH key in the app and did not get prompted for a password, but from my understanding of the changes here, that shouldn't have been the case?

**Comment by fmeum** [comment]
> I tried cloning from a server which only had password authentication after setting authentication mode to SSH key in the app and did not get prompted for a password, but from my understanding of the changes here, that shouldn't have been the case?

Yes, if that doesn't work and there is nothing else that's wrong here, then I fear sshj doesn't properly deal with multiple auth methods.

Could you send me the sshj log output?

**Comment by msfjarvis** [comment]
> > I tried cloning from a server which only had password authentication after setting authentication mode to SSH key in the app and did not get prompted for a password, but from my understanding of the changes here, that shouldn't have been the case?
> 
> Yes, if that doesn't work and there is nothing else that's wrong here, then I fear sshj doesn't properly deal with multiple auth methods.
> 
> Could you send me the sshj log output?

Obviously simply taking a log made it behave :expressionless:

**Review by msfjarvis — DISMISSED** [review]

**Review by msfjarvis — APPROVED** [review]

**Pull request merged**
