### PR TITLE
complementing & fixing german translations

### PR DESCRIPTION
**Pull request by agrahn**
Missing translations added + some fixes. Empty lines added for easier side-by-side editing with English version.

### CODE REVIEW

**Comment by msfjarvis** [comment]
Translations are done via [Crowdin](https://crowdin.com/project/android-password-store) not GitHub PRs, I'll manually upload this to Crowdin and sync it back so it'll take a bit to merge this.

**Comment by msfjarvis** [comment]
Superseded by #3175

**Comment by agrahn** [comment]
Thank you, I was not aware of crowdin, and apologies for the extra work you had.

**Comment by msfjarvis** [comment]
No worries, it did expose the recently broken Crowdin integration so it's a net positive at the end of the day :)

**Comment by agrahn** [comment]
I can also fill in the translations in Crowdin, just subscribed to it.

**Pull request closed without merging**
