### PR TITLE
refactor support for application overlay in api v >= 26

### PR DESCRIPTION
**Pull request by tarciosaraiva**
@zeapo should fix issue #363 - haven't tested it locally though. Maybe @brainard52 could take some time?

### CODE REVIEW

**Comment by tarciosaraiva** [comment]
Seems like the build failed as it couldn't download the SDK (weird). Here's the output of my local build.

```
→ ./gradlew clean build test lintDebug -Dpre-dex=false

> Configure project :app
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Configuration 'androidTestCompile' in project ':app' is deprecated. Use 'androidTestImplementation' instead.

> Task :app:compileDebugKotlin
Using Kotlin incremental compilation

> Task :app:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/tarciosaraiva/workspace/Android-Password-Store/app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :app:compileReleaseKotlin
Using Kotlin incremental compilation

> Task :app:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/tarciosaraiva/workspace/Android-Password-Store/app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.


Running dex as a separate process.

To run dex in process, the Gradle daemon needs a larger heap.
It currently has 1024 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to at least 1536 MB.
To do this set org.gradle.jvmargs=-Xmx1536M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html


> Task :app:lint
Ran lint on variant debug: 129 issues found
Ran lint on variant release: 129 issues found
Wrote HTML report to file:///Users/tarciosaraiva/workspace/Android-Password-Store/app/build/reports/lint-results.html
Wrote XML report to file:///Users/tarciosaraiva/workspace/Android-Password-Store/app/build/reports/lint-results.xml

> Task :app:lintDebug
Wrote HTML report to file:///Users/tarciosaraiva/workspace/Android-Password-Store/app/build/reports/lint-results-debug.html
Wrote XML report to file:///Users/tarciosaraiva/workspace/Android-Password-Store/app/build/reports/lint-results-debug.xml
Lint found 129 warnings


BUILD SUCCESSFUL in 24s
55 actionable tasks: 54 executed, 1 up-to-date
```

**Comment by brainard52** [comment]
If you can get me the APK I'd be happy to test it.

**Comment by tarciosaraiva** [comment]
@brainard52 awesome [here it goes](https://drive.google.com/file/d/1JYC3ic0eQqOg5KMSuRtBXTr5E2hntEVE/view?usp=sharing)

**Comment by brainard52** [comment]
It works!

**Comment by brainard52** [comment]
It works!

**Comment by tarciosaraiva** [comment]
Awesome, I guess I did something right 👍

**Comment by zeapo** [comment]
Nice

**Pull request merged**
