### PR TITLE
Add "challenge" and "verification" to OTP heuristic terms

### PR DESCRIPTION
**Pull request by fmeum**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description

Add "challenge" and "verification" to OTP heuristic terms, as they are e.g. used by Twitter. There seems to be little potential for misidentification here (which is also why I decided against adding "response").

## :green_heart: How did you test it?
The SMS OTP field in the native Twitter app now shows an Autofill prompt.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by fmeum** [comment]
Shout out to trailing commas, thanks @msfjarvis.

**Comment by fmeum** [comment]
Should I remove the trailing comma for now so that can go in the patch release without Kotlin 1.4?

**Comment by msfjarvis** [comment]
> Should I remove the trailing comma for now so that can go in the patch release without Kotlin 1.4?

I'll handle it when I cherry pick.

**Review by msfjarvis — APPROVED** [review]

**Comment by msfjarvis** [comment]
In the Twitter PWA I'm not getting an Autofill prompt on the 'Enter your password' screen presented when I tried to enable SMS OTP. Might wanna investigate that as well.

**Comment by fmeum** [comment]
> In the Twitter PWA I'm not getting an Autofill prompt on the 'Enter your password' screen presented when I tried to enable SMS OTP. Might wanna investigate that as well.

I am getting the prompt there with 1.10.1. Do other Autofill apps trigger for you on that field? It is quite clearly marked as a password field, so Password Store's Autofill does recognize it if given the chance by the system.

**Comment by msfjarvis** [comment]
> > In the Twitter PWA I'm not getting an Autofill prompt on the 'Enter your password' screen presented when I tried to enable SMS OTP. Might wanna investigate that as well.
> 
> I am getting the prompt there with 1.10.1. Do other Autofill apps trigger for you on that field? It is quite clearly marked as a password field, so Password Store's Autofill does recognize it if given the chance by the system.

I'll check again, maybe it was just a fluke.

**Pull request merged**
