### PR TITLE
Switch to URL-based Git config and refactor Git settings

### LINKED ISSUE #1002: [BUG] Unable to properly enter bitbucket git server settings in version 1.11.0-SNAPSHOT
**Describe the bug**
Cannot get proper git server settings to utilize app connection to remote bitbucket repo

**To Reproduce**
1. Attempt to enter bitbucket git server settings under settings
2. no matter what combo of username, server URL and Repo Path I get error messages suggesting git settings are set up wrong
3. Instead of git@bitbucket.org:klebane/password_store.bare.git I get errors when I try to sync that say repo path was klebane@git@bitbucket.org/password_store.bare.git

**Expected behavior**
In legacy version of password store I can enter proper server settings

**Screenshots**

**Device information (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: gentoo
 - App version 1.11.0 SNAPSHOT vs 1.3.3 (legacy)

**Additional context**

### PR DESCRIPTION
**Pull request by fmeum**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## :scroll: Description

This PR
* replaces the Git config fields with a simple "Repository URL" field.
* migrates existing configs to the new single-pref approach on startup.
* converts all Git settings into smart properties of a static `object`.
* refactors `SharedPreferences.getString` uses to rely on a consistent, idiomatic way of handling `null` values.
* retrieves the SSH username directly from the URL, which gets rid of quite a bit of code.

## :bulb: Motivation and Context

Most people treat repository URLs as opaque identifiers that come after `git clone`, so we shouldn't ask them to split them up into their atomic parts. This is especially important since "username" is ambiguous when referring to e.g. a GitHub URL.

The refactoring was due since global settings should be separated from `Activity` related code and do not require complex dependency injection.

## :green_heart: How did you test it?
Lightly. We should extensively test the migration.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

**Review by msfjarvis — DISMISSED** [review]
WHEW, that was a big review. I wanna experiment a bit with the protocol option UX so I'd prefer to roll that into this as well if you don't mind.

**Comment by fmeum** [comment]
> WHEW, that was a big review. I wanna experiment a bit with the protocol option UX so I'd prefer to roll that into this as well if you don't mind.

Well, sorry for that. One thing came to the other and this ended up as a large-scale refactor. 
I don't mind and would also wait with further testing until that's done.

**Comment by msfjarvis** [comment]
> > WHEW, that was a big review. I wanna experiment a bit with the protocol option UX so I'd prefer to roll that into this as well if you don't mind.
> 
> Well, sorry for that. One thing came to the other and this ended up as a large-scale refactor.

Oh please don't be, I LOVE the final look of this.

> I don't mind and would also wait with further testing until that's done.

:+1:

**Comment by msfjarvis** [comment]
UI idea didn't pan out :(

**Review by msfjarvis — APPROVED** [review]

**Review by Skrilltrax — APPROVED** [review]

**Pull request merged**
