### PR TITLE
Refactor PasswordRepository and simplify uses

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## :scroll: Description
Begin cleaning up and refactoring usage of `PasswordRepository` methods as a preliminary step for a larger revamp of how this is handled.

## :bulb: Motivation and Context
This class is a bit of a kludge and getting this into a better shape is critical to improving the general infrastructure of the app.

## :pencil: Checklist

- [ ] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [ ] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by msfjarvis** [comment]
I tried getting this to work properly but the existing labyrinth of terrible code is just too complex and brittle. I'm probably going to end up with salvaging what can be saved of the `:app` module and kicking off development from scratch in a separate application module.

**Comment by Skrilltrax** [comment]
Are you planning to build everything from scratch?

**Comment by msfjarvis** [comment]
> Are you planning to build everything from scratch? 

The view layer at least, will pull in the existing "new" code as and when that builds out.

**Comment by Skrilltrax** [comment]
Oh cool, let me know If you need any help :)

**Pull request closed without merging**
