### PR TITLE
Update to SSHJ 0.31.0

### LINKED ISSUE #1294: [BUG] BouncyCastle is required to read a key of type ecdsa-sha2-nistp521
**Describe the bug**
I can't clone my repository because the key used is of type ecdsa-sha2-nistp521 and it seems it's not supported. Openkeychain works fine, I tried to decrypt a message and it works.

**To Reproduce**
1. Open Password Store
2. Click on 'Let's go'
3. Click on 'Clone Remote Repo'
4. Enter repository URL and branch
5. Select Openkeychain as authentication method
6. Click 'Clone'
7. Select the key from Openkeychain
8. Error: BouncyCastle is required to read a key of type ecdsa-sha2-nistp521

**Expected behavior**
I expected the repository to be cloned

**Device information (please complete the following information):**
 - Device: Xiaomi Redmi Note 8 Pro
 - OS: Lineage OS 17.1 unofficial ROM
 - App version 1.13.2

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [x] Dependency updates

## :scroll: Description
Updates to SSHJ 0.31.0 and ensures that the activity result launcher is unregistered on the correct thread.

This is incomplete as of now because it appears that SSHJ wants keys to implement `java.security.interfaces.ECKey`
which I am not too sure of how to go about.

```
Dying because - dev.msfjarvis.aps.util.git.sshj.OpenKeychainKeyProvider$makePrivateKey$1 cannot be cast to java.security.interfaces.ECKey
```

## :bulb: Motivation and Context
Fixes #1294

## :green_heart: How did you test it?
Verified I don't crash with the exception in #1294 or observe the incorrect unregistration in my logs.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by fmeum** [comment]
I have a fix and will pick this up, thanks for starting it.

**Comment by fmeum** [comment]
I have tested this with P-521 and RSA keys after I had made my changes and they work fine. I have not checked yet whether AES-GCM is actually being used.

**Review by fmeum — APPROVED** [review]

**Comment by msfjarvis** [comment]
Works for me as well, merging.

**Comment by msfjarvis** [comment]
```
Negotiated algorithms: [ kex=curve25519-sha256; sig=ssh-ed25519; c2sCipher=aes128-gcm@openssh.com; s2cCipher=aes128-gcm@openssh.com; c2sMAC=hmac-sha2-512-etm@openssh.com; s2cMAC=hmac-sha2-512-etm@openssh.com; c2sComp=none; s2cComp=none; rsaSHA2Support=false ]
```

Does this mean AES-GCM is working?

**Comment by fmeum** [comment]
> ```
> Negotiated algorithms: [ kex=curve25519-sha256; sig=ssh-ed25519; c2sCipher=aes128-gcm@openssh.com; s2cCipher=aes128-gcm@openssh.com; c2sMAC=hmac-sha2-512-etm@openssh.com; s2cMAC=hmac-sha2-512-etm@openssh.com; c2sComp=none; s2cComp=none; rsaSHA2Support=false ]
> ```
> 
> Does this mean AES-GCM is working?

It does :-)

**Pull request merged**
