### PR TITLE
treewide: Refactor uses of platform APIs to AndroidX

### PR DESCRIPTION
**Pull request by MSF-Jarvis**
Also cleanup some deprecation issues with menu classes

### CODE REVIEW

**Comment by MSF-Jarvis** [comment]
`java.lang.ClassCastException: org.openintents.openpgp.util.OpenPgpAppPreference cannot be cast to androidx.preference.Preference` ugh. The source [repo](https://github.com/open-keychain/openpgp-api) looks pretty dead to me, so how about forking the library and fixing it up for AndroidX instead? I'll happily maintain said fork.

**Comment by zidhuss** [comment]
I'd rather we contribute back to that repository if the changes we make will benefit them also.

**Comment by MSF-Jarvis** [comment]
> I'd rather we contribute back to that repository if the changes we make will benefit them also.

There's trivial PRs that are pending for months now which leads ne to believe the library is unmaintained

**Comment by zidhuss** [comment]
I see. Maybe try reaching out to them with an issue in the main repository? https://github.com/open-keychain/open-keychain

**Comment by MSF-Jarvis** [comment]
> I see. Maybe try reaching out to them with an issue in the main repository? [open-keychain/open-keychain](https://github.com/open-keychain/open-keychain)
> […](#)
> On Thu, Jan 03, 2019 at 03:04:52AM -0800, Harsh Shandilya wrote: > I'd rather we contribute back to that repository if the changes we make will benefit them also. There's trivial PRs that are pending for months now which leads ne to believe the library is unmaintained -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#467 (comment)](https://github.com/zeapo/Android-Password-Store/pull/467#issuecomment-451113108)

Will give that a try

**Comment by zeapo** [comment]
You can ask either @dschuermann or @Valodim about how to proceed. Their repository is not dead, and I fee like a a PR there would benefit all of us ^_^

**Comment by MSF-Jarvis** [comment]
No progress at open-keychain's end on this :(

**Comment by zeapo** [comment]
You think that it's that complicated to Implement a version with AndroidX and propose it as a PR?

**Comment by MSF-Jarvis** [comment]
A direct port is going to be a royal pain in the ass because I've explored it already. Maybe if we reimplement from zero we'll be able to concoct something better that works. Going to give it a go over the weekend and report back.

**Comment by MSF-Jarvis** [comment]
Superseded by #519

**Pull request closed without merging**
