### PR TITLE
Autofill: add support for Bromite and Ungoogled Chromium

### PR DESCRIPTION
**Pull request by djpohly**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description

Added [Bromite](https://www.bromite.org/) (org.bromite.bromite) and [Ungoogled Chromium](https://git.droidware.info/wchen342/ungoogled-chromium-android) (org.ungoogled.chromium.stable) to the list of autofill-able browsers.  Since these are pretty direct Chromium mods, I assume they fall into the same categories as com.android.chrome.

## :bulb: Motivation and Context

This allows more browsers to benefit from the autofill feature.

## :green_heart: How did you test it?
I don't currently have space to install the Android SDK, so I'm marking this as a draft until I have the opportunity (may be a while).  If someone could at least build an APK for testing, that would be awesome.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (:set ts=4 sw=4 et)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

**Review by msfjarvis — APPROVED** [review]

**Comment by fmeum** [comment]
Thanks for the PR! I'll be able to test this and verify the hashes on Monday.

**Comment by msfjarvis** [comment]
I've verified the hashes, I'll test the individual apps later today and merge this.

**Comment by msfjarvis** [comment]
Had a world of pain triggering Autofill so these are all right up the Chromium alley...

**Comment by fmeum** [comment]
@djpohly We are considering extracting the Oreo Autofill service part into a library for other projects to use. Since the GPL is very restrictive as a license for libraries, we would like to make the code available under an additional, slightly more permissive license, which would be either the LGPL or the MPL. Would you consent to the code you added with this PR being made available under one of those two licenses?

**Comment by djpohly** [comment]
Yes, that's fine! I assign all ownership/rights of this contributed code to the android-password-store project.

**Comment by msfjarvis** [comment]
> Yes, that's fine! I assign all ownership/rights of this contributed code to the android-password-store project.

Awesome, thanks a lot!

**Pull request merged**
