### PR TITLE
Allow configuring pull behavior

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [ ] Bugfix
- [x] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description
This PR allows configuring the pull behavior for JGit through the Git utils screen. While we were here,
I also went ahead and resolved a couple UX related issues I noticed. Git server config activity will
no longer request focus each time you open it, matching the behavior of Git config activity which only
does so when things are unconfigured. We also now have a password toggle for the git credential input
dialog similar to all the other input fields that accept confidential data.

## :bulb: Motivation and Context
The ability to configure pull behavior was requested in #836.

## :green_heart: How did you test it?
UX improvements were verified by manual checks, pull behavior remains untested. @Schueni1 will have to
step in and help verify this works as he expects it to.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :camera_flash: Screenshots / GIFs

<details>
<summary>Password Toggle</summary>

Password Toggle

</details>

### CODE REVIEW

**Comment by msfjarvis** [comment]
[Here's](https://dl.msfjarvis.dev/testing-snapshot/aps_1.9.0-SNAPSHOT.apk) a signed snapshot build off this branch.

**Review by Skrilltrax — DISMISSED** [review]

**Review by fmeum — DISMISSED** [review]

**Comment by msfjarvis** [comment]
Don't wanna merge this before @Schueni1 has had the chance to test :/

**Comment by Schueni1** [comment]
Works great!

**Comment by msfjarvis** [comment]
> I encountered a couple problems with this snapshot. When I change to rebase instead of merge I get the following error:

This is exactly what I was concerned about :/

> And every time I tap on a password it opens it immediately in editing mode.

That's odd, I'll take a look...

**Comment by msfjarvis** [comment]
I've rebased out the UI/UX changes here as they're now in #851. It seems merging in JGit is not as straightforward as I had hoped, but it's doable. Just not sure how to handle merge conflicts :/

**Comment by FabianHenneke** [comment]
> I've rebased out the UI/UX changes here as they're now in #851. It seems merging in JGit is not as straightforward as I had hoped, but it's doable. Just not sure how to handle merge conflicts :/

Since all files are encrypted anyway, I would ideally like to have a dialog for every merge conflict that  asks me whether I want to keep the on-device or in-repo version of the file, corresponding to `--ours` and `--theirs`. Every mistake could easily be fixed afterwards on a computer since the repos would at least have become compatible.

**Comment by msfjarvis** [comment]
> > I've rebased out the UI/UX changes here as they're now in #851. It seems merging in JGit is not as straightforward as I had hoped, but it's doable. Just not sure how to handle merge conflicts :/
> 
> Since all files are encrypted anyway, I would ideally like to have a dialog for every merge conflict that asks me whether I want to keep the on-device or in-repo version of the file, corresponding to `--ours` and `--theirs`. Every mistake could easily be fixed afterwards on a computer since the repos would at least have become compatible.

Not sure if that can be pulled off with how GitOperation is structured atm. Will give it a go after I resolve #845.

**Comment by msfjarvis** [comment]
I'm not making much progress on this front nor do I need this feature so I'll let someone else resolve this.

**Pull request closed without merging**
