### PR TITLE
Make git username and email configurable

### LINKED ISSUE #286: Make git username and email configurable
Git commits made by `root` user `<root@localhost>`

### PR DESCRIPTION
**Pull request by shanavas786**
closes #286

### CODE REVIEW

**Comment by Horgix** [comment]
Wow.

I needed that for a few months now, and just decided today that it might be worth opening a issue and maybe try to contribute the username and email handling.

What a nice surprise to see that it was done just yesterday :)
Thanks a lot @shanavas786 !

**Comment by zeapo** [comment]
Thanks for the PR @shanavas786 

Could you tell me when you finish working on it so that I try it?

**Comment by shanavas786** [comment]
@Horgix always welcome :smile: 

@zeapo It is finished, that is why I removed WIP from the title.
Its my first contribution to an android application. please review :)

**Comment by zeapo** [comment]
Sorry for the delay. I will merge it, but it will go through the refactoring I am starting for the git activity.

**Comment by Horgix** [comment]
Any idea when this will be released @zeapo ?
I guess you're trying to get it into the `1.2.0.57` release?

**Comment by zeapo** [comment]
I will put a new pre-release (beta channel on Play Store) x.58 this week

**Comment by Horgix** [comment]
Nice, thanks @zeapo :)

Out of curiosity, will you put this pre-release on F-Droid too? (I'm getting it from there)

**Comment by zeapo** [comment]
it's automatic. whenever I tag the new version, F-Droid will build it. However you won't see "pre-release" on F-Droid :/

**Comment by shanavas786** [comment]
Enabling Unstable updates in f-droid will do it.

**Comment by zeapo** [comment]
I meant from our side. But it seems like if we tag with `-alpha` or `-beta` it should work.

**Pull request merged**
