### PR TITLE
Add failing test for keys generated with GPG 2.37

### LINKED ISSUE #2179: [BUG] Keys with AEAD algorithms set cannot be used with the app
### Describe the bug

I am using the APS-freeRelease-2.2.0.0-SNAPSHOT (from 11.10.2022 (dd.mm.yyyy))

GPG Key Pair is created on MacOS using the --openpgp Flag.

As soon as I select a Password to decrypt and enter the Password for the Secret Key the following Exception is thrown:

```
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: app.passwordstore.crypto.errors.UnknownError
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at app.passwordstore.data.crypto.CryptoRepository.access$decryptPgp(SourceFile:353)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at app.passwordstore.data.crypto.CryptoRepository$decrypt$2.invokeSuspend(SourceFile:35)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:109)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(SourceFile:13)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:77)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: Caused by: java.util.NoSuchElementException: No direct-key signature and no user-id signature found.
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at org.pgpainless.key.info.KeyRingInfo.getPrimaryKeyExpirationDate(SourceFile:128)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at org.pgpainless.key.info.KeyRingInfo.getEncryptionSubkeys(SourceFile:1)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at org.pgpainless.decryption_verification.DecryptionStreamFactory.processPGPEncryptedDataList(SourceFile:674)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at org.pgpainless.decryption_verification.DecryptionStreamFactory.processPGPPackets(SourceFile:17)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at org.eclipse.jgit.lib.IndexDiff$1.withOptions(SourceFile:408)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	at app.passwordstore.data.crypto.CryptoRepository.access$decryptPgp(SourceFile:285)
10-12 15:06:47.788  4634  4634 E StandaloneCoroutine: 	... 6 more
```

I am using `pass` on Mac and that works ok.
I suspect an issue with my GPG Key Pair but ran out of ideas on what to check / change.

### Steps to reproduce

1. Go to Passwords
2. Click on Password to be decrypted
3. Enter Secret Password
4. Message appears saying that the Password is wrong but it is not.

### Expected behavior

It should display the encrypted password

### Screenshots

_No response_

### Device information

- Device: [Sony Xperia XZ2 Compact]
- OS: [Lineage 19.1]
- App version [e.g. 3.1.0]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by msfjarvis**
Fixes #2179

### CODE REVIEW

**Comment by msfjarvis** [comment]
@vanitasvitae This is a failure case for GPG keys with AEAD algorithms set that PGPainless can correctly import but not decrypt with. We hit this limitation with OpenKeychain [some time ago](https://github.com/android-password-store/Android-Password-Store/discussions/1429#discussioncomment-3490909) and while there is a manual workaround available I was wondering if this is something that needs to be fixed in PGPainless/BC. More information and another set of keys to test against is in #2179.

**Comment by vanitasvitae** [comment]
GnuPGs way of doing AEAD is non-standard. There has been quite a bit of heated discussion on the IETF OpenPGP mailing list about AEAD recently, which is definitely worth a read.

Further, BC only added support for some type of AEAD in OpenPGP very recently (in 1.72 I believe).
In PGPainless I haven't yet come around to integrate support for it and honestly, I'd like to wait for the dust to settle and for the OpenPGP spec-team to come to a single, standardized solution before wasting time on a non-standard implementation :)

**Comment by vanitasvitae** [comment]
[This thread](https://mailarchive.ietf.org/arch/msg/openpgp/yayGaIen3DW6ixwrJkP-QcAcFSQ/) is worth a read, even though it is quite noisy.

**Comment by msfjarvis** [comment]
> GnuPGs way of doing AEAD is non-standard. There has been quite a bit of heated discussion on the IETF OpenPGP mailing list about AEAD recently, which is definitely worth a read.
> 
> Further, BC only added support for some type of AEAD in OpenPGP very recently (in 1.72 I believe). In PGPainless I haven't yet come around to integrate support for it and honestly, I'd like to wait for the dust to settle and for the OpenPGP spec-team to come to a single, standardized solution before wasting time on a non-standard implementation :)

Yeah that makes sense. I'll just let a future PGPainless update take care of this then. Thanks for the link!

**Comment by naisanzaa** [comment]
Is there a way to take how iOS is handling GPG keys with AEAD?

It seems to handle them just fine

**Comment by msfjarvis** [comment]
> Is there a way to take how iOS is handling GPG keys with AEAD?
> 
> It seems to handle them just fine

The answer was already given: "I'd like to wait for the dust to settle and for the OpenPGP spec-team to come to a single, standardized solution before wasting time on a non-standard implementation :)"

Please stop necro-posting in old threads about this if you've also filed a new issue.

**Pull request closed without merging**
