### PR TITLE
Prepare v1.11.3 release

### PR DESCRIPTION
**Pull request by msfjarvis**
Backports #1062, strips the `-free` version suffix.

### CODE REVIEW

**Comment by fmeum** [comment]
Thanks, will update the F-Droid PR once the release artifacts have been generated.

**Comment by fmeum** [comment]
The release is in a draft status now, are you doing the rest manually?

**Comment by msfjarvis** [comment]
> The release is in a draft status now, are you doing the rest manually?

The release is built as a draft by default so I can double check before everybody gets notified, I'm uploading to Play Store right now.

**Comment by fmeum** [comment]
The verification of our release builds fails with an error message. Not sure what's up there, it used to work and the CI workflow hasn't changed, right?
```
2020-08-27 15:52:10,362 WARNING: Ignoring META-INF/MANIFEST.MF from unsigned/dev.msfjarvis.aps_11130.apk
DOES NOT VERIFY
ERROR: JAR signer CERT.RSA: JAR signature META-INF/CERT.SF indicates the APK is signed using APK Signature Scheme v2 but no such signature was found. Signature stripped?
2020-08-27 15:52:11,498 ERROR: 
/tmp/tmp2h845_px/sigcp_dev.msfjarvis.aps_11130.apk: 
2020-08-27 15:52:11,498 INFO: ...NOT verified - /tmp/tmp2h845_px/sigcp_dev.msfjarvis.aps_11130.apk
I: Using Apktool 2.4.0-dirty on dev.msfjarvis.aps_11130.binary.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/fhenneke/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Using Apktool 2.4.0-dirty on sigcp_dev.msfjarvis.aps_11130.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/fhenneke/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
2020-08-27 15:52:24,664 DEBUG: > diff -r /tmp/tmp2h845_px/unsigned_binaries_dev.msfjarvis.aps_11130.binary /tmp/tmp2h845_px/_tmp_tmp2h845_px_sigcp_dev.msfjarvis.aps_11130
2020-08-27 15:52:24,976 DEBUG: removing unsigned/dev.msfjarvis.aps_11130.apk
2020-08-27 15:52:24,979 DEBUG: removing unsigned/binaries/dev.msfjarvis.aps_11130.binary.apk
2020-08-27 15:52:25,273 ERROR: Could not build app dev.msfjarvis.aps: compared built binary to supplied reference binary but failed
==== detail begin ====
Unexpected diff output:
diff -r /tmp/tmp2h845_px/unsigned_binaries_dev.msfjarvis.aps_11130.binary/apktool/apktool.yml /tmp/tmp2h845_px/_tmp_tmp2h845_px_sigcp_dev.msfjarvis.aps_11130/apktool/apktool.yml
2c2
< apkFileName: dev.msfjarvis.aps_11130.binary.apk
---
> apkFileName: sigcp_dev.msfjarvis.aps_11130.apk
==== detail end ====
```

**Comment by fmeum** [comment]
Posted the error log here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6998#note_403260965

**Comment by msfjarvis** [comment]
Don't really know what's up with this, the CI workflow is definitely the same and we've not had any major AGP bumps that'd change it.

**Pull request merged**
