### PR TITLE
Fix lint warnings

### PR DESCRIPTION
**Pull request by felixb**
Fix a lot of lint errors and warnings.
Most things are automatically applied fixes done with android studio:    
* externalize strings
* remove unused code / classes / layouts / imports
* migrate some fields to local variables
* remove code commented out long ago (2nd commit)

There are basically no changes in code logic or what so ever.

```
$ ./gradlew lintDebug
[..]
Lint found 28 errors, 396 warnings
```

refs #233

### CODE REVIEW

**Comment by zeapo** [comment]
Could you please resolve the conflict, I'll merge it once done.

Thanks

**Comment by felixb** [comment]
I just pushed the rebased commits and added a 3rd. Here is what I tested with the current HEAD:

[x] browse items/folders
[x] open item
[x] move item
[x] open settings
[x] activate autofill

**Comment by felixb** [comment]
With current HEAD we are down to:

```
$ ./gradlew lintDebug
[..]
Lint found 34 errors, 103 warnings
```

32 errors are incomplete translations.

**Comment by zeapo** [comment]
Thank you for the huge contribution

**Pull request merged**
