### PR TITLE
Update strings.xml: Added missing spaces

### PR DESCRIPTION
**Pull request by nikelborm**

### CODE REVIEW

**Comment by msfjarvis** [comment]
Thanks for the PR, we only accept localization updates through Crowdin so I've applied this PR's changes there: https://crowdin.com/project/android-password-store/ru

**Comment by nikelborm** [comment]
So why they are in repo then?

**Comment by msfjarvis** [comment]
> So why they are in repo then?

Because they need to be there in order to be included in the app.

**Comment by nikelborm** [comment]
Do you push source code of 3rd-party dependencies to the repo? Or their compiled versions? I don't think so. Even if they also needed to be included in the app, they are not in repo, but only the files to keep track of them.

Translation files in repo should be synced somehow with crowdin, because you updated them in crowdin but in the repo there are old versions still present.

Or they should be pulled from crowdin as 'repo init' command or as 'pre-build' command.

They are either part of the repo and their changes are tracked by version control system, or they are not and pulled at compiled-time|runtime.

The case of pulling them at runtime have their upsides, because you can freely update your translation and deliver them fast to users without building and waiting for approvals of stores (google, apple, etc). Many backends+frontends are this way and have translation endpoints and translations in database or have CDN with .json files that are pulled during usage of frontend. But of course if you don't have backend, this is not an option (except for pulling them as static files from github pages etc).

**Comment by msfjarvis** [comment]
> Do you push source code of 3rd-party dependencies to the repo? Or their compiled versions? I don't think so. Even if they also needed to be included in the app, they are not in repo, but only the files to keep track of them. Translation files should be synced somehow, because you updated them in crowdin but in the repo there are old version still. Or they should be pulled from crowdin as 'repo init' command or as 'pre-build' command. They are either part of the repo and their changes are tracked by version control system, or they are not and pulled at compiled-time|runtime. The case of pulling them at runtime have their upsides, because you can freely update your translation and deliver them fast to users without building and waiting for approvals of stores (google, apple, etc). Many backends+frontends are this way and have translation endpoints and translations in database or have CDN with .json files that are pulled during usage of frontend

Translations are [synced automatically](https://github.com/android-password-store/Android-Password-Store/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged+label%3AA-localisation) [every week](https://github.com/android-password-store/Android-Password-Store/actions/workflows/sync_crowdin.yml).

**Comment by nikelborm** [comment]
So maybe configure crowdin to call this github action using [webhooks](https://developer.crowdin.com/webhooks/#suggested-translation-added)?

**Comment by msfjarvis** [comment]
> So maybe configure crowdin to call this github action using [webhooks](https://developer.crowdin.com/webhooks/#suggested-translation-added)?

I prefer my setup.

**Comment by nikelborm** [comment]
ok, got it

**Pull request closed without merging**
