### PR TITLE
fix null pointer exception when using public only keys (#3143)

### LINKED ISSUE #3143: public only keys cause null pointer exception
### Describe the bug

When using multiple keys and one of the keys is a public only key, a null pointer exception occurs when attempting to decrypt a password file.

In my setup, the password files are encrypted with two public keys, allowing either associated private key to decrypt the file.  So a user needs their private key for decryption and both their public key and the other public key for encryption.  Private key files contain both the private and public keys.  A public key file contains only the public key.   It looks like the code is assuming that the key files always contain both private and public keys.

### Steps to reproduce

1. Import  a private key
2. Import public only key
3. Attempt to decrypt a password file using the private key password
4. The Password dialog will report "Wrong password"
5. The log file shows a null pointer exception in PGPSecretKeyRingCollection

### Expected behavior

A password file should be able to be successfully decrypted when a public only key has been imported in addition to a private/public key.

### Screenshots

_No response_

### Device information

- App version: 2.0.0-SNAPSHOT

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gregrenda**
Don't call PGPSecretKeyRingCollection for public only keys

### CODE REVIEW

**Comment by msfjarvis** [comment]
Please add a test for it here https://github.com/android-password-store/Android-Password-Store/blob/develop/crypto/pgpainless/src/test/kotlin/app/passwordstore/crypto/PGPainlessCryptoHandlerTest.kt

**Comment by msfjarvis** [comment]
I had some time so I tried to adapt an existing test to reproduce this but couldn't get it to fail without your fix, feel free to build upon this or write your own test. It should fail on `develop` and pass on this branch.

```kotlin
  @Ignore("Should fail when decrypting but completes successfully")
  @Test
  fun decryptWithPublicKeys() {
    val aliceSecKeyRing =
      PGPainless.generateKeyRing().modernKeyRing("Alice <owner@example.com>", KEY_PASSPHRASE)
    val bobSecKeyRing = PGPainless.generateKeyRing().modernKeyRing("Bob <owner@example.com>", KEY_PASSPHRASE)
    val aliceCert = PGPainless.extractCertificate(aliceSecKeyRing)
    val aliceKey = PGPKey(PGPainless.asciiArmor(aliceCert).encodeToByteArray())
    val bobKey = PGPKey(PGPainless.asciiArmor(bobSecKeyRing).encodeToByteArray())

    val ciphertextStream = ByteArrayOutputStream()
    val encryptRes =
      cryptoHandler.encrypt(
        listOf(aliceKey, bobKey),
        PLAIN_TEXT.byteInputStream(Charsets.UTF_8),
        ciphertextStream,
        PGPEncryptOptions.Builder().withAsciiArmor(true).build(),
      )
    assertTrue(encryptRes.isOk)

    val message = ciphertextStream.toByteArray().decodeToString()
    val info = MessageInspector.determineEncryptionInfoForMessage(message)
    assertTrue(info.isEncrypted)
    assertEquals(2, info.keyIds.size)
    assertFalse(info.isSignedOnly)

    assertFails {
      val ciphertextStreamCopy = message.byteInputStream()
      val plaintextStream = ByteArrayOutputStream()
      cryptoHandler.decrypt(
        listOf(aliceKey, bobKey),
        KEY_PASSPHRASE,
        ciphertextStreamCopy,
        plaintextStream,
        PGPDecryptOptions.Builder().build(),
      )
    }
  }
```

**Comment by gregrenda** [comment]
Added a unit test.  You have to pass both private and public keys to decrypt simultaneously to trigger the bug.  You probably shouldn't be passing public keys to decrypt but that's likely a bigger change.

**Review by msfjarvis — APPROVED** [review]
Thanks for the quick turnaround!

**Pull request merged**
