### PR TITLE
Backport fixes to release

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [x] Backports

## :scroll: Description
Backports #880 and #885 to release

### CODE REVIEW

**Comment by msfjarvis** [comment]
need to remember to pass `release` as upstream to `gh` -_-

**Comment by fmeum** [comment]
We should also include #884 and maybe generalize the changelog entry by saying that this affects all old-style keys with passphrases, regardless of whether they are empty or not.

**Comment by msfjarvis** [comment]
> We should also include #884 and maybe generalize the changelog entry by saying that this affects all old-style keys with passphrases, regardless of whether they are empty or not.

Done, should be good to go now.

**Review by fmeum — DISMISSED** [review]
LGTM and ready to go once @Schueni1 has confirmed the fix.

**Comment by msfjarvis** [comment]
Had to include this because of the test failures

**Review by fmeum — APPROVED** [review]

**Pull request merged**
