### PR TITLE
Improve Git error message handling

### PR DESCRIPTION
**Pull request by fmeum**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description

Simplifies Git error handling, includes the Throwable class name for unknown errors, and adds a special case for `UnknownHostException`.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

**Review by msfjarvis — DISMISSED** [review]

**Comment by fmeum** [comment]
@msfjarvis Could you verify that this latest commit doesn't lead to a crash when a GitException is triggered?

**Comment by msfjarvis** [comment]
> @msfjarvis Could you verify that this latest commit doesn't lead to a crash when a GitException is triggered?

Sure

**Comment by msfjarvis** [comment]
It doesn't crash, but it does put the exception name into the error message which I'm slowly realising I'm not a fan of :(

**Comment by fmeum** [comment]
Is this better now? I am not going through `Exception.message` anymore.

**Review by msfjarvis — APPROVED** [review]

**Comment by msfjarvis** [comment]
All good now

**Comment by fmeum** [comment]
> All good now

Ah, I thought you were referring to something else. I introduced this change specifically because it would have helped with the `UnknownHostException`, which previously resulted in a message consisting of the hostname only. I would thus find the exception name quite helpful in errors for which we don't yet produce a more helpful error message, but don't mind if you would rather not expose class names to users.

**Comment by msfjarvis** [comment]
> > All good now
> 
> Ah, I thought you were referring to something else. I introduced this change specifically because it would have helped with the `UnknownHostException`, which previously resulted in a message consisting of the hostname only. I would thus find the exception name quite helpful in errors for which we don't yet produce a more helpful error message, but don't mind if you would rather not expose class names to users.

The class name isn't really helpful for most of our users IMO. The UnknownHostException special casing is good and I'd prefer we just explicitly handle all the exceptions whose default messages are not useful.

**Pull request merged**
