### PR TITLE
Remember HTTPS password throughout a sync operation

### PR DESCRIPTION
**Pull request by fmeum**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description

Remember the HTTPS password throughout a sync operation.

## :bulb: Motivation and Context

The current state could be viewed as having just a UI issue (the second prompt is marked with the "Wrong passphrase" error), but since it counts as a retry in our `PasswordFinder` implementation, this also removes the stored passphrase, which is a bit more of a nuisance. I'm labeling this as backport for that reason, but am not a 100% sure.

## :green_heart: How did you test it?
Sync operations succeed with only a single password prompt.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

**Review by msfjarvis — DISMISSED** [review]

**Comment by msfjarvis** [comment]
Was hoping to avoid a v1.11.3 but that's certainly not happening now. Will queue backports and a release tonight. Anything special that needs to go in for F-Droid? Now's the time.

**Comment by fmeum** [comment]
> Was hoping to avoid a v1.11.3 but that's certainly not happening now. Will queue backports and a release tonight. Anything special that needs to go in for F-Droid? Now's the time.

Getting rid of the version name suffix would help, I don't think anything else is needed at this time.

**Review by msfjarvis — APPROVED** [review]

**Comment by fmeum** [comment]
@msfjarvis Could you also test password authentication a bit more before the release? I used `https://try.gitea.io` for that purpose.

**Comment by msfjarvis** [comment]
> @msfjarvis Could you also test password authentication a bit more before the release? I used `https://try.gitea.io` for that purpose.

Yeah I'll test it when I do the backports.

**Pull request merged**
