### PR TITLE
Disable SSH multiplexing if not supported

### LINKED ISSUE #1092: [BUG] unable to synchronize repository
**Describe the bug**
Synchronizing the repository throws an error: "An error occurred during a Git operation. cannot open additional channels". 
However, the separate "push to remote" and "pull from remote" commands work well.

**To Reproduce**
1. Open menu
2. Click on 'Synchronize repository'
3. Enter SSH passphrase
4. See error dialog

**Device information (please complete the following information):**
 - Device: Xiaomi Mi A3
 - OS: Android 10.0
 - App version: 1.11.3

### PR DESCRIPTION
**Pull request by fmeum**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description

Fall back to single channel SSH connections if the server (looking at you, Bitbucket) does not support multiplexing.

## :bulb: Motivation and Context

Should fix #1092 when it's done.

## :green_heart: How did you test it?
~~Not yet.~~ Create a private Bitbucket repository, clone it to the device, attempt to synchronize after creating a new password and get the error about broken multiplexing then trying again correctly uses a pull + push separately.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by fmeum** [comment]
This is my attempt at fixing #1092. It is not completely consistent with how we sync (it's missing the occasional sync commit, which we may want to include in the PullOperation anyway) and untested. @msfjarvis Could you take over from here?

**Comment by msfjarvis** [comment]
> This is my attempt at fixing #1092. It is not completely consistent with how we sync (it's missing the occasional sync commit, which we may want to include in the PullOperation anyway) and untested. @msfjarvis Could you take over from here?

Sure thing.

**Comment by fmeum** [comment]
That story is 5/5.

**Comment by msfjarvis** [comment]
Works for me now, but the double authentication w/ keystore-backed SSH keys sure is annoying. Get your shit together Bitbucket.

**Review by msfjarvis — DISMISSED** [review]

**Comment by fmeum** [comment]
> Works for me now, but the double authentication w/ keystore-backed SSH keys sure is annoying. Get your shit together Bitbucket.

We *could* get around this by only showing the prompt if the reauth timeout hasn't passed. As it is currently at 30 or 15 seconds, that should mostly work unless the user is on a really slow connection.

**Comment by msfjarvis** [comment]
> > Works for me now, but the double authentication w/ keystore-backed SSH keys sure is annoying. Get your shit together Bitbucket.
> 
> We _could_ get around this by only showing the prompt if the reauth timeout hasn't passed. As it is currently at 30 or 15 seconds, that should mostly work unless the user is on a really slow connection.

I'd rather just let it be at this point.

**Comment by msfjarvis** [comment]
If the macOS runner is gonna be slow af anyway might as well get the trivial stuff done too.

**Review by msfjarvis — APPROVED** [review]

**Pull request merged**
