### PR TITLE
Make autofill-parser API explicit and refactor

### LINKED ISSUE #1167: Enable Kotlin explicit API mode in autofill parser
Kotlin 1.4 comes with an [explicit API mode](https://kotlinlang.org/docs/reference/whatsnew14.html#explicit-api-mode-for-library-authors) that requires all public API of a Kotlin library to be marked as public manually and to be provided with concrete, user-defined types as opposed to relying on automatic type inference. Our openpgp-ktx﻿ library already utilises this feature, and we should have autofill-parser follow suit.

While here, it might also make sense to flesh out the documentation.

### PR DESCRIPTION
**Pull request by fmeum**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## :scroll: Description

Adds explicit visibility markers to `autofill-parser`.

`FilledForm`'s `scenario` member is now of type
`AutofillScenario<AutofillId>` in order to properly hide the internal
type `FormField`.

## :green_heart: How did you test it?
Still compiles.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :crystal_ball: Next steps

Expand documentation.

### CODE REVIEW

**Comment by fmeum** [comment]
@msfjarvis Is there a way to purge the cached API data?

**Comment by msfjarvis** [comment]
> @msfjarvis Is there a way to purge the cached API data?

`./gradlew apiDump` should update it.

**Comment by fmeum** [comment]
I added some convenience functions and renamed a method with an appropriate @Deprecation annotation.

**Comment by msfjarvis** [comment]
Setting this as blocked for now since the regression from #1181 needs to be resolved first.

**Review by msfjarvis — APPROVED** [review]

**Pull request merged**
