### PR TITLE
Adding support for Git's simple protocol

### PR DESCRIPTION
**Pull request by abdelq**
## :loudspeaker: Type of change
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description
Git offers a simple TCP server for repositories using [`git-daemon`](https://git-scm.com/docs/git-daemon). This adds support for it.

## :bulb: Motivation and Context
Tried to clone a repository from my local network and found out it wasn't supported.

## :green_heart: How did you test it?
On my phone with the daemon on the LAN as originally wanted.

## :pencil: Checklist
- [ ] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by msfjarvis** [comment]
The `git://` protocol is completely unencrypted so I'm not very keen on supporting it in the app, but I'll wait for Fabian to weigh in as well. I'd have preferred if you filed an issue first before spending time on this :(

**Comment by abdelq** [comment]
I'm aware of it, but if someone is using it, they most likely already know about that. In my case it's through Wireguard between two trusted devices. Maybe worth adding a confirmation message about it?

**Comment by msfjarvis** [comment]
> I'm aware of it, but if someone is using it, they most likely already know about that.

If only :( Most users of `git://` I've encountered did not actually know that it's insecure.

> In my case it's through Wireguard between two trusted devices. Maybe worth adding a confirmation message about it?

A user prompt might be a good middle ground, but I suggest waiting for the other maintainers to weigh in before you put any more effort into this PR.

**Comment by fmeum** [comment]
@abdelq Could you briefly describe the concrete use case for `git://` support in APS? When can this particular protocol be used, but the others can't?

As @msfjarvis has said, I'm not convinced the majority of our users would expect a protocol named after git to be unencrypted.

**Comment by abdelq** [comment]
@fmeum

> Could you briefly describe the concrete use case for `git://` support in APS?

My personal preference as a knowledgeable user to keep things simple.

> When can this particular protocol be used, but the others can't?

Generally speaking, none.

> As @msfjarvis has said, I'm not convinced the majority of our users would expect a protocol named after git to be unencrypted.

I get your point of view hence mentioning maybe adding a confirmation prompt, but if you really don't want to include support for it, it should be explicitly marked as unsupported instead of the generic "The provided repository URL is not valid".

**Pull request closed without merging**
