### PR TITLE
show age for passwords in detail view

### PR DESCRIPTION
**Pull request by chrboe**
Implements #330.
This fetches the latest commit where the respective password file was
changed from the current HEAD and outputs the relative time since
the last change on the decrypt page.

NOTE: translations are incomplete because I only speak so many languages :)
If someone hits me up with other translations I'll be happy to include them
in this PR.

### CODE REVIEW

**Comment by zeapo** [comment]
Thanks for the PR. However I do not want to introduce any "git" logic in the decryption / encryption process. Especially if we want (and will) support non-git stores.

**Comment by chrboe** [comment]
That's understandable. So do you suggest just getting the last changed date from the actual file if it's a non-git store then?

**Comment by zeapo** [comment]
In the case of git repository we should keep the commit technique. However I'd like it to be "outside" PgpActivity as it should be agnostic to what store it's in. Especially that in a near future it won't open any file, it will just receive bytearray and decrypt/encrypt them :)

Maybe you could move the logic in PasswordStore, and pass the age (in days) as an intent data to PgpActivity?

**Comment by chrboe** [comment]
Yes, that would seem like a sensible enough approach. I'll see if I can find some time to take a stab at this today

**Comment by zeapo** [comment]
Thanks for the update, I will try it later today :)

**Comment by zeapo** [comment]
Sorry for the delay @chrboe , I will take care of your PR with the two others ASAP :)

**Comment by zeapo** [comment]
Sorry but I will merge this after we handle the Autofill issue

**Comment by zeapo** [comment]
@chrboe could you please rebase so that I merge this :)

**Comment by chrboe** [comment]
Sure thing, I'm on it :) Thanks for taking the time to review this!

**Comment by chrboe** [comment]
Phew, at last. I had a few issues along the way, but it should be all fine now.

**Pull request merged**
