### PR TITLE
SSH key generator

### PR DESCRIPTION
**Pull request by wongma7**
For #43. New option in Settings 'Generate ssh-key' will create a private key .ssh_key in the same location an import would put one and will also create a public key .ssh_key.pub in that directory. The public key is shown to the user immediately after generation so that they can share it with their git server. Also, the dialog that appears when a user attempts git operations without having an ssh key (when ssh key is set as their authentication mode) has been changed to have 'import' & 'generate' options as opposed to just 'ok'/import.
Goal here is to handle & generate just one ssh key pair to make it easier for users to get things set up from the app. More complicated handling of keys I think won't be necessary until multiple repos are supported & hopefully another app to handle it will be available by then... 
To-dos:
1. Let the user export/see the public key whenever they want. Can this be an additional item in the settings? And the public key should be deleted/not shown if a new private key is imported & overwrites the original private key.
2. There are lots of skipped frames when 'Generate' is pressed.

### CODE REVIEW

**Comment by wongma7** [comment]
Okay, done I think. So there are now 'generate ssh key' and 'view generated ssh key' options. The latter option is always visible but enabled/disabled appropriately

**Comment by zeapo** [comment]
Nice! That was a needed feature.

Do you think it is possible to support multiple pairs of keys? That way, once we implement the multiple stores mode, we let the user select which keys to use.

I play with it this WE, I merge then tag a new version with these awesome new features.

**Comment by wongma7** [comment]
Sure, I can work on that. Now that I think about it, it should not be too difficult. I am thinking of a single 'choose ssh key' preference where you can choose/generate/import private keys or key pairs. Then simply store the name of the preferred key in a preference.

**Comment by zeapo** [comment]
The passphrase should have a password style and a monospaced font. With a small checkbox to show the passphrase.

**Pull request merged**
