### PR TITLE
Replace Timber with logcat

### LINKED ISSUE #1505: Replace Timber with logcat
Currently the app and all other libs are using `Timber` for logging. Timber itself is pretty nice and solves a ton of issues but now Square released a new logging library called `logcat`.

Logcat improves upon timber and hence we should migrate to it.

https://github.com/square/logcat for reference.

### PR DESCRIPTION
**Pull request by pt2121**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## :bulb: Motivation and Context

Fixes #1505

## :pencil: Checklist

- [x] I formatted the code `./gradlew spotlessApply`
- [x] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by msfjarvis** [comment]
@pt2121 do you want me to review this? Draft indicates you're still working on it but I don't see any action items in your PR description.

**Comment by pt2121** [comment]
@msfjarvis I finished it late last night and wanted to do more tests. There are probably a couple things I'd like to run by you tho - will let you know.
(I will continue after work.)

**Comment by pt2121** [comment]
@msfjarvis This is ready for review. One small thing I want to call out is I had to manually add tags in a couple places for standalone functions.

**Comment by Skrilltrax** [comment]
LGTM, I just have one suggestion. Instead of writing 
```
logcat { "message\n${e.asLog()}" }
```

What if we overload the `asLog` to take a message parameter?

```
logcat { e.asLog("message") }
```

@msfjarvis @pt2121?

**Comment by msfjarvis** [comment]
> LGTM, I just have one suggestion. Instead of writing
> 
> ```
> logcat { "message\n${e.asLog()}" }
> ```
> 
> What if we overload the `asLog` to take a message parameter?
> 
> ```
> logcat { e.asLog("message") }
> ```
> 
> @msfjarvis @pt2121?

I'd be down for it, @pt2121 can you add the extension to `app/src/main/java/dev/msfjarvis/aps/util/extensions/Extensions.kt` and switch all uses to it?

**Comment by pt2121** [comment]
Yeah, will update. good idea

**Comment by pt2121** [comment]
Updated!

**Review by Skrilltrax — APPROVED** [review]
Looks good to me! Thanks for the pull request @pt2121

**Pull request merged**
