### PR TITLE
Autofill: add support for Cromite

### PR DESCRIPTION
**Pull request by C0unt-zero**
## Description
Cromite, a Bromite fork, was recently released.
Added [Cromite](https://github.com/uazo/cromite) (org.cromite.cromite) to the list of autofill-able browsers.

### Related issue
https://github.com/uazo/cromite/issues/123

### CODE REVIEW

**Comment by msfjarvis** [comment]
Chromium browsers need to be added [here](https://github.com/android-password-store/Android-Password-Store/blob/4a1d6721b2a597cc7b91662c867c86be77812295/autofill-parser/src/main/java/com/github/androidpasswordstore/autofillparser/FeatureAndTrustDetection.kt#L160) as well.

I'm not sure I really wanna add Cromite just yet or at all really, a fork-of-a-fork with basically no community standing and [an FAQ that still talks about Bromite](https://github.com/uazo/cromite/blob/3f31d6687df2166ab2ea589f526486296ea83d47/FAQ.md) seems like it needs some time to figure itself out. It looks like [the project owner holds a similar opinion](https://github.com/uazo/bromite-buildtools/issues/77#issuecomment-1641697451).

**Comment by msfjarvis** [comment]
Yeah I don't think I wanna add this, Cromite is too early stage for me to be able to make an informed decision on its trustworthiness. I'm open to re-evaluating it in a few months (6 seems reasonable?) and you can re-submit the PR then.

**Comment by Kuchteq** [comment]
Hi, I think that cromite has stood the test of time, could we perhaps reevaluate this?

**Comment by msfjarvis** [comment]
> Hi, I think that cromite has stood the test of time, could we perhaps reevaluate this?

Well I did say I'd like to wait six months but since Bitwarden is already considering it, I'll let them make a call and follow suit.

**Comment by octvs** [comment]
>  I'll let them make a call and follow suit.

They did https://github.com/bitwarden/mobile/pull/2640#issuecomment-1839520245

**Comment by msfjarvis** [comment]
> > I'll let them make a call and follow suit.
> 
> They did [bitwarden/mobile#2640 (comment)](https://github.com/bitwarden/mobile/pull/2640#issuecomment-1839520245)

I'll take a PR :)

**Pull request closed without merging**
