### PR TITLE
Fix totp elements layout

### PR DESCRIPTION
**Pull request by balasankarc**
TOTP element was overlapping `username` label. This PR fixes it
  
Before (see how TOTP is above Username):
before

After:
after

### CODE REVIEW

**Comment by zeapo** [comment]
Thanks for the PR.
What would happen if there's no username? Wouldn't that leave a space above TOTP?

**Comment by balasankarc** [comment]
@zeapo True. It will. I had thought about it. Unfortunately that bug is a pre-existing one, one that predates introduction of totp logic. If an entry has extra content and no username, there will be a blank space above extra content.

I will think about how we can fix it quickly, but for now I just focused on getting totp usable and didn't think about the aesthetics much.

**Comment by balasankarc** [comment]
@zeapo I think 8c270f5 fixes it.

**Comment by zeapo** [comment]
looks good, thanks

**Pull request merged**
