### PR TITLE
Redo authentication modes UI with Chips

### LINKED ISSUE #1261: [BUG] When setting up a new repository, not all authentication modes fit on the screen
**Describe the bug**
"Openkeychain" is smushed compared to the other two authentication modes.

**To Reproduce**
1. Get a Samsung Galaxy S7 (I'm not sure if this is caused by the smaller screen size or the older OS)
2. Open the app.
3. Click "Clone remote repo"
4. See screenshot

**Expected behavior**
"openkeychain" should either be abbreviated or shrunk to fit the screen. 

**Screenshots**
foo

**Device information (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android 8.0
 - App version 1.13.1

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description
Splits out our themes to `themes.xml` and switches the Git server config screen to use [Material Design Chips](https://material.io/components/chips) to denote individual authentication modes.

## :bulb: Motivation and Context
We have had numerous complaints about the buttons being too wide for certain screens and thus getting cut off (such as #1261). Chips are inherently designed to be multiline so we willhopefully never have that problem again.

## :green_heart: How did you test it?
Verified functionality is still intact and behavior is same as before.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :camera_flash: Screenshots / GIFs

<details><summary>Screenshot of new auth modes chips</summary>

New chips based UI for selecting authentication mode

</details>

### CODE REVIEW

**Comment by msfjarvis** [comment]
The exact UI is up for debate, I simply fixed up my migration from months ago and made it semi-pretty.

**Comment by msfjarvis** [comment]
@fmeum @Skrilltrax this is good to go from my end.

**Comment by Skrilltrax** [comment]
@msfjarvis can we use outlined chips and filled chip for selected auth mode?

**Comment by msfjarvis** [comment]
> @msfjarvis can we use outlined chips and filled chip for selected auth mode?

It'll need a theme change at runtime to happen which I very much doubt is worth the trouble.

**Review by Skrilltrax — APPROVED** [review]

**Pull request merged**
