### PR TITLE
Fix Autofill publisher changed layout

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description
Fix dark-on-dark text in Autofill publisher changed screen.

## :bulb: Motivation and Context
It's good to see buttons!

## :green_heart: How did you test it?
Verified I can see text in the buttons I previously couldn't.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :camera_flash: Screenshots / GIFs
<details>
<summary>Before</summary>

Previous state

</details>

<details>
<summary>After</summary>

After fix

</details>

### CODE REVIEW

**Comment by msfjarvis** [comment]
I don't think autofill matches are being cleared by the button like they should, so that will need to be looked into and fixed separately.

**Comment by Skrilltrax** [comment]
@msfjarvis can we increase the width of the dialog?

**Comment by msfjarvis** [comment]
> @msfjarvis can we increase the width of the dialog?

Probably

**Comment by Skrilltrax** [comment]
I'll update the UI, I think I have a few other changes too.

**Comment by msfjarvis** [comment]
> I'll update the UI, I think I have a few other changes too.

Sure, assigning to you then.

**Comment by fmeum** [comment]
> I don't think autofill matches are being cleared by the button like they should, so that will need to be looked into and fixed separately.

Do you mean the advanced info reset button? Can you say which behavior you are observing?

**Comment by Skrilltrax** [comment]
<details>

<summary>First</summary>



</details>

<details>

<summary>Second</summary>



</details>

**Comment by msfjarvis** [comment]
> > I don't think autofill matches are being cleared by the button like they should, so that will need to be looked into and fixed separately.
> 
> Do you mean the advanced info reset button? Can you say which behavior you are observing?

Yeah, it didn't appear to actually clear the matches. I had to kill the app being autofilled and retry autofill before I was able to see matches.

**Review by msfjarvis — COMMENTED** [review]
LGTM

**Review by Skrilltrax — APPROVED** [review]

**Comment by fmeum** [comment]
> Yeah, it didn't appear to actually clear the matches. I had to kill the app being autofilled and retry autofill before I was able to see matches.

Okay, I looked into it and think that we are hitting a fundamental Autofill design restriction here: The datasets returned by the Autofill service are cached and there doesn't seem to be a way to flush this cache. What this means is that even after the matches have been correctly cleared, there is no way for us to have new datasets generated (replacing the "Publisher changed" one) simply because we are never given a new FillRequest.

I will see whether I can come up with a workaround. @msfjarvis Alternatively, do you see a way to communicate this to users clearly?

**Comment by msfjarvis** [comment]
> > Yeah, it didn't appear to actually clear the matches. I had to kill the app being autofilled and retry autofill before I was able to see matches.
> 
> Okay, I looked into it and think that we are hitting a fundamental Autofill design restriction here: The datasets returned by the Autofill service are cached and there doesn't seem to be a way to flush this cache. What this means is that even after the matches have been correctly cleared, there is no way for us to have new datasets generated (replacing the "Publisher changed" one) simply because we are never given a new FillRequest.
> 
> I will see whether I can come up with a workaround. @msfjarvis Alternatively, do you see a way to communicate this to users clearly?

I'm afraid not. Though clearly phishing attempts are rare enough for nobody to ever report the glaring UI problem so maybe it's not worth looking too deeply into.

**Pull request merged**
