### PR TITLE
Consolidate password list refresh

### PR DESCRIPTION
**Pull request by fmeum**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## :scroll: Description

Replace refreshPasswordList and resetPasswordList with a single function that resets navigation only if necessary, namely if the
current directory no longer exists.
This function is now also called mostly from PasswordStore, whereas previously refresh and reset calls were made from many different places in the code base, sometimes twice, sometimes ineffectively.

@msfjarvis There is a remaining issue to fix: The sync operation does not return with the correct request code (105), but with 65535. As a result, just as before, no refresh/reset happens after a sync operation while everything works as expected after a pull operation.

## :bulb: Motivation and Context

Password list refresh and reset is currently handled all over the place in our code base and not handled correctly in all cases.

## :green_heart: How did you test it?
I verified that the correct kind of refresh is performed after moves, password creations, push and pull operations, but this needs more testing.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :crystal_ball: Next steps

Come up with a good changelog entry once we know whether we can fix the sync issue.

### CODE REVIEW

**Comment by msfjarvis** [comment]
> @msfjarvis There is a remaining issue to fix: The sync operation does not return with the correct request code (105), but with 65535. As a result, just as before, no refresh/reset happens after a sync operation while everything works as expected after a pull operation.
>
Hm I think I encountered this while refactoring PasswordStore to use ActivityResultContracts, I'll push a fix to this PR when I get to my PC for testing this.

**Comment by msfjarvis** [comment]
20 minutes of frustrating println debugging later I got nothing :/

**Comment by fmeum** [comment]
> 20 minutes of frustrating println debugging later I got nothing :/

It is really weird that the behavior differs between sync and pull. I don't see any activity-related difference between the two operations.

If we really can't figure this out, how about adding a fixme comment and calling reset in an else branch? It's ugly, but I'm out of other ideas.

**Comment by msfjarvis** [comment]
> > 20 minutes of frustrating println debugging later I got nothing :/
> 
> It is really weird that the behavior differs between sync and pull. I don't see any activity-related difference between the two operations.
> 
> If we really can't figure this out, how about adding a fixme comment and calling reset in an else branch? It's ugly, but I'm out of other ideas.

Yeah I think that's gonna do for now, hopefully ActivityResultContracts will eliminate this when I finish the migration.

**Comment by fmeum** [comment]
The refresh is also run when an unexpected request code is encountered (with an appropriate FIXME comment).

**Review by msfjarvis — APPROVED** [review]

**Pull request merged**
