### PR TITLE
Migrate to AndroidX

### PR DESCRIPTION
**Pull request by MSF-Jarvis**
Depends on #429, I've split the PRs in case AndroidX migration is not on the cards for now.

### CODE REVIEW

**Comment by zeapo** [comment]
:+1:

**Comment by MSF-Jarvis** [comment]
The build failure apparently needs a cache flush over at Travis-CI since I can't reproduce it on a clean VM.

**Comment by zeapo** [comment]
@MSF-Jarvis there are some conflicts. I'll take a look at travis later today.

**Comment by MSF-Jarvis** [comment]
I'll go rebase this

**Comment by MSF-Jarvis** [comment]
I also took the liberty to sort some imports in `PgpActivity.kt`, will be following up with a more comprehensive Kotlin migration PR.

**Comment by MSF-Jarvis** [comment]
Build should be fixed with this.

**Comment by zeapo** [comment]
Nice! I didn't know about Jetpack, seems that it improves the code readability.

Let @zidhuss know when you're ok with your changes, so that he can test them.

**Comment by MSF-Jarvis** [comment]
@zeapo I'm done here, no more changes coming into this branch. Further contributuons will be in separate PRs.

**Comment by zidhuss** [comment]
Looks good to me. Thanks for your contribution @MSF-Jarvis !

**Pull request merged**
