### PR TITLE
Have Travis build an AVD before running the install.

### PR DESCRIPTION
**Pull request by pirogoeth**
I got the Travis builds closer to working (#65), you just have to bring your tests up to date and hopefully the builds will start succeeding! 

I would go a bit farther with it, but I'm trying to get about five million things done this morning.  Hope this helps!

### CODE REVIEW

**Comment by zeapo** [comment]
seems like it is working (except tests that I have to update)

**Comment by zeapo** [comment]
could you follow the project on Assembly and claim the bounty https://assembly.com/aps-android-password-store/bounties/1 ?

**Comment by pirogoeth** [comment]
Awesome.

**Comment by zeapo** [comment]
still got an issue (https://travis-ci.org/zeapo/Android-Password-Store), but probably linked to the tests. I will disable them and see that on a separate branch.

**Pull request merged**
