### PR TITLE
Reintroduce TOTP support

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description
Re-introduces TOTP support backed by extensive automated tests.

## :bulb: Motivation and Context
Users have been very unhappy about losing support for OTP features and while HOTP is very ugly to add,
TOTP is a relatively easier effort so as a good compromise between maintainability and user experience,
this PR reintroduces support for TOTP secrets.

## :green_heart: How did you test it?
Users are testing this with their TOTP secrets and reporting back with success, and all our unit and instrumentation tests pass.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :crystal_ball: Next steps
Follow the patterns established here to break more things down to testable units

### CODE REVIEW

**Comment by msfjarvis** [comment]
Well kill me now, the click listener refuses to fire :D

**Comment by msfjarvis** [comment]
Good news: the tests have been verified with a separate app to be correct which means my Kotlin port of the Otp class works well
Bad news: I can't make this work in the app because my click listener never fires :|

**Comment by msfjarvis** [comment]
Uhh this works now for some reason? @erayd @charvp @Helianthella here's a signed build to test the functionality and UX with: https://dl.msfjarvis.dev/share/aps_1.10.0-SNAPSHOT.apk

**Comment by chvp** [comment]
Thanks! I've logged into a few sites, seems to work without a hitch.

**Comment by msfjarvis** [comment]
I think this covers our bases well. If someone has more `otpauth://` URI samples they wanna share to be added to these tests I'd be very grateful.

**Comment by erayd** [comment]
@msfjarvis Initial testing with that APK seems to work well - I've tested a number of different entries, and the generated codes were all correct.

One comment - there is no option to view the generated OTP code; the only option is to copy it to the clipboard. For those who are logging in on a device that isn't their phone, that will cause problems. Displaying it in a similar manner to how the password and username are displayed would address that issue.

**Comment by msfjarvis** [comment]
> One comment - there is no option to view the generated OTP code; the only option is to copy it to the clipboard. For those who are logging in on a device that isn't their phone, that will cause problems. Displaying it in a similar manner to how the password and username are displayed would address that issue.

Yeah that makes sense, will get on it.

**Comment by msfjarvis** [comment]
@erayd same link, I've updated the APK in-place. Let me know if this flow works.

**Comment by fmeum** [comment]
@msfjarvis I'll take a look at the OTP code now and streamline the UI flow a bit.

**Comment by erayd** [comment]
@msfjarvis Looks better. Two points:

1. The code doesn't update properly - it should change to the new code when the previous one expires.

2. The UI is quite different to that used for username / password, and requires an extra button press. Is there a reason for that? IMO it would be logical for the UI to be consistent.

**Comment by erayd** [comment]
One other observation - the "View OTP" button is still present, even for entries which do not contain a TOTP seed.

**Comment by erayd** [comment]
@FabianHenneke Looking at your unit tests - some seeds are longer than the ones you're using, and some seeds require right-padding in order to be complete (they aren't valid base32 otherwise). Both of those scenarios would be useful to include in tests.

**Comment by fmeum** [comment]
I fixed some crashes and am now showing the OTP in the same way as the username. It is updated every 30 seconds.

The following todos are left and I will probably not get to them today:

1. The TOTP is updated for as long as the lifecycleScope is alive. Is that okay?
2. We might want to hide the `otpauth://` line from the extra contents like we do for the username.
3. Ensure compatibility with longer and unpadded secrets as @erayd suggested in https://github.com/android-password-store/Android-Password-Store/pull/890#issuecomment-650720094.

**Comment by erayd** [comment]
Thanks @FabianHenneke 🙂.

1. Assuming that `lifecycleScope` means "as long as everything else in the entry is viewable", that seems reasonable.

2. Seems reasonable, provided it's still visible when editing. Wanting to copy the OTP *seed* rather than the generated code is a very rare use-case.

**Comment by msfjarvis** [comment]
> 2. Seems reasonable, provided it's still visible when editing. Wanting to copy the OTP _seed_ rather than the generated code is a very rare use-case.

You can still manually copy it while editing so IMO our current setup is fine.

I've made the change to drop `otpauth://` lines from the extra content, and changed the snackbar text to mention OTP codes since I added the string before anyway.

**Comment by erayd** [comment]
> I've made the change to drop otpauth:// lines

Does that commit also drop `totp:` lines? That wasn't obvious from looking at the commit, unless I missed something.

**Comment by msfjarvis** [comment]
> > I've made the change to drop otpauth:// lines
> 
> Does that commit also drop `totp:` lines? That wasn't obvious from looking at the commit, unless I missed something.

No, just `otpauth://`. I'll add in `totp://`.

**Comment by erayd** [comment]
Not `totp://` - just `totp:`

It's not a URL scheme, but rather a key / value line, similar to how the username is encoded.

**Comment by msfjarvis** [comment]
> Not `totp://` - just `totp:`
> 
> It's not a URL scheme, but rather a key / value line, similar to how the username is encoded.

Ah yeah, accidentally typed `totp://` here. Pushed the fix.

**Comment by msfjarvis** [comment]
If I understand Base32 padding correctly (don't let me down Wikipedia), this test covers that case as well which means this is good to go now.

**Comment by TheLastProject** [comment]
I implemented parsing otpauth URLs in pyotp, so maybe the unit tests there may help too: https://github.com/pyauth/pyotp/blob/master/test.py#L342

**Comment by TheLastProject** [comment]
See also https://github.com/pyauth/pyotp/pull/84 for the feature itself and the checks to ensure the URL meets the standards

**Review by fmeum — DISMISSED** [review]

**Comment by msfjarvis** [comment]
> I implemented parsing otpauth URLs in pyotp, so maybe the unit tests there may help too: [pyauth/pyotp:test.py@`master`#L342](https://github.com/pyauth/pyotp/blob/master/test.py#L342)

Thanks a lot, this is helpful! This gave me a couple ideas that I'll implement right now.

**Comment by msfjarvis** [comment]
@FabianHenneke reverted as per our discussion

**Review by fmeum — APPROVED** [review]

**Pull request merged**
