### PR TITLE
Better guidance for users to deal with host key changes

### LINKED ISSUE #1232: [BUG] Change Hostkey external git repo, could not be verified
**Describe the bug**
I have an own server, hosting my external git-repo for password-store. The ssh-hostkey has changed, and now my andoid app says "Could not verify ssh-rsa-cert-v01@openssh.com host key with fingerpring...."
I'm not able to say ok to the new hostkey (i know, it changed, because I made the new key)

**To Reproduce**
1. Change ssh Hostkey on remote server for git repo
2. Click on "Git pull"
3. See error

**Expected behavior**
I expected on a new hostkey, that i get asked if i know, that hostkey has changed and i want to say "yes" or "no" to the new hostkey. When i sey "yes", the hostkey-fingerprint for this host should be updated.

**Screenshots**

**Device information (please complete the following information):**
 - Device: HUAWAI P30Pro
 - OS: Android 10
 - App version: 1.13.1

**Additional context**

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description
Improves handling of host key changes by warning the user directly and deleting our local copy.

## :bulb: Motivation and Context
Fixes #1232

## :green_heart: How did you test it?
Connected to a server with an ed25519 host key, then switched it to an RSA key and was prompted to acknowledge the changed host key.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :camera_flash: Screenshots

<details>
<summary>No existing host key</summary>

screenshot-20201210-171324

</details>

<details>
<summary>Host key exists</summary>

screenshot-20201210-171343

</details>

### CODE REVIEW

**Review by fmeum — DISMISSED** [review]
I'm somewhat torn on whether or not it's okay to delete the stored host key right away. I think I would prefer a button in Git settings that clears the key and a warning that directs the user there, but can also live with the current situation. Feel free to merge this if you prefer it this way.

**Comment by msfjarvis** [comment]
> I'm somewhat torn on whether or not it's okay to delete the stored host key right away. I think I would prefer a button in Git settings that clears the key and a warning that directs the user there, but can also live with the current situation. Feel free to merge this if you prefer it this way.

If you feel this should be more intentional then that's fine, I'll make the changes.

**Comment by fmeum** [comment]
> > I'm somewhat torn on whether or not it's okay to delete the stored host key right away. I think I would prefer a button in Git settings that clears the key and a warning that directs the user there, but can also live with the current situation. Feel free to merge this if you prefer it this way.
> 
> If you feel this should be more intentional then that's fine, I'll make the changes.

Thanks!

**Comment by msfjarvis** [comment]
I've made the changes and added screenshots to the PR body, things still work on my end.

**Review by fmeum — APPROVED** [review]

**Pull request merged**
