### PR TITLE
Show recently used passwords

### PR DESCRIPTION
**Pull request by Dioxo**
## :loudspeaker: Type of change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description

Some progress on this feature

At the moment it only has the basic function of showing the last 5 passwords that the user has selected, and it orders them according to the Most Recently Used.

It's just a sample of how it can work, I'm still not sure if to leave the "recent passwords" in the same place as the "passwords", and I don't know for the moment how to send the user to decrypt the password from this list. And there are also bugs like always showing the recent passwords even if the path is not the root. 

I also keep looking how to use `PasswordItemRecyclerAdapter` to reuse the adapter, but I think there are some features that are not needed in this case, like being able to search for them or select more than 1.

I want to know what you think about this way of organizing the passwords, and also if it's a good idea to use `PasswordItemRecyclerAdapter` or create another adapter for this case.

## :bulb: Motivation and Context

#535 

## :green_heart: How did you test it?
I opened some passwords and the list should of recent passwords is updated and reorganized.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by msfjarvis** [comment]
Sorry I haven't been able to find time for reviewing this thoroughly yet, but I'm not sure why there is a LinkedList in there. Sorting by recently used is a massive pain because you'll need to account for parent directories as well and sort them too. I don't believe we'll actually be able to combine both the adapters.

**Comment by Dioxo** [comment]
I was trying to recreate an algorithm that I found with LinkedList, but I could change it to ArrayList or something like that.
And currently, I only take into account the password when it enters in `decryptPassword`, then I add file's path inside the list.
I'll see tomorrow how to manage the adapter, just to know, it'll be better to only display the file's path and when user clicks it, send him to decrypt? Or should I also take into consideration the search and select for more than  1 passwords inside this list? (Like the same behavior that we already have when displaying passwords and categories)

**Comment by msfjarvis** [comment]
> I was trying to recreate an algorithm that I found with LinkedList, but I could change it to ArrayList or something like that.

From my experience you almost never really need a linked list in real life so yeah please consider reimplementing it.

> And currently, I only take into account the password when it enters in `decryptPassword`, then I add file's path inside the list.

That's perfectly fine.

> I'll see tomorrow how to manage the adapter, just to know, it'll be better to only display the file's path and when user clicks it, send him to decrypt? Or should I also take into consideration the search and select for more than  1 passwords inside this list? (Like the same behavior that we already have when displaying passwords and categories)

Ideally you'd sort the entire passwords list and they would behave exactly like they do right now. The only difference between both sorting modes should be just that, the sorting. Everything else should be absolutely identical.

**Comment by fmeum** [comment]
If possible, I would also prefer a solution that just adds a new sort order to the existing adapter and does not introduce any new UI/adapter classes.

Maybe have all X most recently used passwords on top and then sort everything else in the default order specified in the settings?

**Comment by Dioxo** [comment]
I think we could use a tree to manage the passwords.

Like having the folder `/store` as root and if it's a passwords is a node without children, if it's a category is node with category as root and with all the childrens as the passwords inside. 
And mantain the ordrer from the tree, the first child is the most recently used passwords, the second is the second recently used and so on...
At first, the tree will have the alphabetic order but after each password use , the tree will change to reorder.

In your opinion, is this a good approach?
And like that I don't add another UI/Adapter class.

**Comment by fmeum** [comment]
> I think we could use a tree to manage the passwords.
> 
> Like having the folder `/store` as root and if it's a passwords is a node without children, if it's a category is node with category as root and with all the childrens as the passwords inside. 
> And mantain the ordrer from the tree, the first child is the most recently used passwords, the second is the second recently used and so on...
> At first, the tree will have the alphabetic order but after each password use , the tree will change to reorder.
> 
> In your opinion, is this a good approach?
> And like that I don't add another UI/Adapter class.

That's a good mental model of what we need to achieve. A way to maintain this tree implicitly would be to store the last time of use for a given password/category (identified by its path or hash of path) in a shared preferences file separate from the default one. Then, whenever a category is shown, all entries contained in it could be sorted by this time (and then another criterion).

**Comment by Dioxo** [comment]
I don't know which type is going to be working the tree, I think it's PasswordItem because the adapter is using it, but correct me if I'm wrong.

And I don't find where we are currently sending the passwords to the adapter, I don't know from where is the passwords coming from to let the adapter look for it. Could you help me with this?

**Comment by Dioxo** [comment]
I'll close this PR because I think I know how to do this in a different way.

**Pull request closed without merging**
