### PR TITLE
Clipboard now is cleared after manual copy and Spanish translation is added

### PR DESCRIPTION
**Pull request by reroman**
The password now is cleared in both cases, when is manually and automatically copied to clipboard. Also if the option is deactivated, only show the message "The Password is copied to clipboard". This fix the issue #374. Also, Spanish translation was added.

### CODE REVIEW

**Comment by zidhuss** [comment]
@reroman thanks for the pull request!

Could you update your Spanish translations for the git commit messages to make use of format strings? As in: https://github.com/zeapo/Android-Password-Store/blob/master/app/src/main/res/values/strings.xml#L25.

**Comment by zidhuss** [comment]
Is this also related to #186?

**Comment by reroman** [comment]
> @reroman thanks for the pull request!
> 
> Could you update your Spanish translations for the git commit messages to make use of format strings? As in: https://github.com/zeapo/Android-Password-Store/blob/master/app/src/main/res/values/strings.xml#L25.

Ok, no problem.

**Comment by zidhuss** [comment]
Hey @reroman, again thanks for your contribution. I thought it would be best to split this pull request as it includes two separate changes, i.e. clearing the clipboard and the Spanish translation.

I went and added the translations to the master branch (e58a5e7). Could you rebase and open a new pull request with the clipboard clearing code (6b8ac9a)?

**Pull request closed without merging**
