### PR TITLE
Added the ability to make an invisible password visible

### PR DESCRIPTION
**Pull request by danielvandenberg95**
Added the ability to make an invisible password visible using a button, and added some rough translations.

This allows you to hold down a button to see the password while it's being hidden. From personal experience, when using the password store in combination with https://github.com/danielvandenberg95/BluetoothToPc and with passwords set to invisible, this can be very convenient.

### CODE REVIEW

**Comment by danielvandenberg95** [comment]
I've got the idea someone broke travis…

**Comment by danielvandenberg95** [comment]
Can I force a travis re-run somehow?

**Comment by zeapo** [comment]
AFAIK only if you push force or create a new commit, sry :/

**Comment by danielvandenberg95** [comment]
http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

Close and reopen apparently helps :)

**Pull request merged**
