### PR TITLE
Revamp onboarding logic 

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## :scroll: Description
Tear out the repository initialization logic from `PasswordStore` and house it in its own activity to separate some of the spaghetti.

## :bulb: Motivation and Context
This code is an absolute disaster, and requires us to constantly patch things in bad ways (#1022 et al) which just makes the whole thing a buggy mess.

## :pencil: Checklist

- [ ] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [ ] I reviewed submitted code
- [ ] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

### CODE REVIEW

**Comment by msfjarvis** [comment]
Other than the lint failure, my only real "big" issue is that both the `checkLocalRepository` methods in `PasswordStore` are referenced in `OnboardingActivity`, but I can't seem to make enough sense of them to refactor and move them out.

**Comment by msfjarvis** [comment]
The last remaining problem here is that we do not allow users who create their repositories locally to be able to push them, because `PasswordRepository#isGitRepo` is false for them.

```diff
diff --git app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
index 7ea213957e10..3d0d460641a7 100644
--- app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
+++ app/src/main/java/com/zeapo/pwdstore/utils/PasswordRepository.kt
@@ -92,10 +92,7 @@ open class PasswordRepository protected constructor() {
         @JvmStatic
         fun isGitRepo(): Boolean {
             if (repository != null) {
-                // Check if remote exists
-                return repository!!.config.getSubsections("remote").isNotEmpty() &&
-                    repository!!.objectDatabase.exists() &&
-                    repository!!.allRefs.isNotEmpty()
+                return repository!!.objectDatabase.exists()
             }
             return false
         }
```

This would fix it, but I'm not sure of the downsides.

**Comment by msfjarvis** [comment]
I'm also open to be convinced that we require the ability to clone to external storage. I personally see no point to it, since AFAICT external storage is mostly used by people who do not wish to use Git for syncing their passwords.

**Comment by fmeum** [comment]
> I'm also open to be convinced that we require the ability to clone to external storage. I personally see no point to it, since AFAICT external storage is mostly used by people who do not wish to use Git for syncing their passwords.

I would also vote for keeping things separated: either Git is used for syncing and everything happens in-app or some other sync solution is used and APS stays clear of everything sync-related. Any mix of both will only introduce new potential for breakages.

**Review by fmeum — DISMISSED** [review]

**Comment by msfjarvis** [comment]
> > I'm also open to be convinced that we require the ability to clone to external storage. I personally see no point to it, since AFAICT external storage is mostly used by people who do not wish to use Git for syncing their passwords.
> 
> I would also vote for keeping things separated: either Git is used for syncing and everything happens in-app or some other sync solution is used and APS stays clear of everything sync-related. Any mix of both will only introduce new potential for breakages.

Awesome. What do we want to do about the other problem though? I feel we should certainly be allowing users who create repositories inside the app to be able to also push that repository somewhere off-device.

**Comment by fmeum** [comment]
> > > I'm also open to be convinced that we require the ability to clone to external storage. I personally see no point to it, since AFAICT external storage is mostly used by people who do not wish to use Git for syncing their passwords.
> > 
> > 
> > I would also vote for keeping things separated: either Git is used for syncing and everything happens in-app or some other sync solution is used and APS stays clear of everything sync-related. Any mix of both will only introduce new potential for breakages.
> 
> Awesome. What do we want to do about the other problem though? I feel we should certainly be allowing users who create repositories inside the app to be able to also push that repository somewhere off-device.

Sorry, the two open questions became one in my head. I have to admit that I don't the relevant line at all, my git-internals-fu is pretty weak. I would vote for giving it a try in snapshots unless it has a potential to nuke local directories.

**Comment by msfjarvis** [comment]
> > > > I'm also open to be convinced that we require the ability to clone to external storage. I personally see no point to it, since AFAICT external storage is mostly used by people who do not wish to use Git for syncing their passwords.
> > > 
> > > 
> > > I would also vote for keeping things separated: either Git is used for syncing and everything happens in-app or some other sync solution is used and APS stays clear of everything sync-related. Any mix of both will only introduce new potential for breakages.
> > 
> > 
> > Awesome. What do we want to do about the other problem though? I feel we should certainly be allowing users who create repositories inside the app to be able to also push that repository somewhere off-device.
> 
> Sorry, the two open questions became one in my head. I have to admit that I don't the relevant line at all, my git-internals-fu is pretty weak. I would vote for giving it a try in snapshots unless it has a potential to nuke local directories.

I checked with my pre-existing repo and there are no regressions so I think we'll be fine, just need your approval on the PR to merge.

**Review by fmeum — APPROVED** [review]
At your command.

**Pull request merged**
