### PR TITLE
Update gradle and external dependencies

### PR DESCRIPTION
**Pull request by MSF-Jarvis**
- Switch away from deprecated compile directive
- Remove explicit buildToolsVersion, is defined by the gradle plugin now
- Fix build in SelectFolderActivity

Signed-off-by: Harsh Shandilya <harsh@prjkt.io>

### CODE REVIEW

**Comment by zidhuss** [comment]
Thanks for the pull request.

Did you get this to work without breaking Android Studio's instant run?

**Comment by MSF-Jarvis** [comment]
I don't use Instant Run but I don't see how anything here would break it.

**Comment by zeapo** [comment]
That should work. 
@MSF-Jarvis  any reason for gradle 4.6 vs 4.8 (or 4.10.2?)

**Comment by zidhuss** [comment]
I get this when trying to run with Instant Run enabled:

 ```
SHA-256 digest error for org/eclipse/jgit/transport/CredentialsProvider.class
```

**Comment by zeapo** [comment]
@MSF-Jarvis I don't think (maybe I'm wrong) that we need the alpha on the plugin to be able to use a 4.8 or 4.10 (https://developer.android.com/studio/releases/gradle-plugin#3-2-0)

**Comment by MSF-Jarvis** [comment]
Ah, true. Will downgrade the plugin back.

**Pull request merged**
