### PR TITLE
Major UI overhaul and the introduction of a new icon

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## :scroll: Description
Re-do the light theme to be a constant white, make all text input boxes use a consistent and legible accent color for box stroke.

## :bulb: Motivation and Context
The box stroke for text input is currently gray, which is illegible on the dark theme. This PR fixes it up to match our accent color on both light and dark themes, improving legibility and bringing some consistency. The light theme has not had a change in literally years and I decided it was time for some dazzle.

## :green_heart: How did you test it?
Visually

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :camera_flash: Screenshots / GIFs

<details>
<summary>Screenshots</summary>

screenshot-20200705-224218

screenshot-20200706-162008

</details>

### CODE REVIEW

**Review by fmeum — DISMISSED** [review]

**Comment by msfjarvis** [comment]
Gonna attempt a few more changes first.

**Comment by msfjarvis** [comment]
Attached a screenshot that I believe has all the UI aspects that have changed. I'm personally a huge fan of this over the previous, frankly dull colors. Thinking of also doing a contest with some, say $50, prize money to get us a new icon funded by our Open Collective. No better time for a change!

**Comment by msfjarvis** [comment]
This is missing the debug icon for now but it's not a blocker and will be here within the week.

**Comment by msfjarvis** [comment]
Play Store has an annoying tendency to stall updates to listings so I've pushed the new icon and feature graphic just now, allowing sufficient buffer period for it to get approved before we push the 1.10.0 release.

**Comment by fmeum** [comment]
I slightly tweaked the xkpwgen UI, but found everything else to look pretty nice and clean. I also really like the new logo.

**Review by fmeum — APPROVED** [review]

**Pull request merged**
