### PR TITLE
Another batch of UI updates

### PR DESCRIPTION
**Pull request by msfjarvis**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## :scroll: Description
Switches to the Manrope font for the UI, adds a divider to the password list, and shows the parent path on both
directories and passwords. Also updates exclusion rules to dump out more Java-only metadata files from our
APKs to keep binary sizes tamed.

## :bulb: Motivation and Context
I've wanted to switch fonts for a while and only recently came to know of Manrope and immediately liked it. Parent
path inclusion was requested by Fabian.

## :green_heart: How did you test it?
Visually verify the UI changes and diff the sizes of builds from `develop` and this branch to confirm that
the sizes are lower in our branch despite the addition of relatively big fonts.

## :pencil: Checklist

- [x] I formatted the code with the IDE's reformat action (Ctrl + Shift + L/Cmd + Shift + L)
- [x] I reviewed submitted code
- [x] I added a [CHANGELOG](CHANGELOG.md) entry if applicable

## :camera_flash: Screenshots / GIFs

<details>
<summary>Screenshots</summary>

screenshot-20200720-014319
screenshot-20200720-005739
screenshot-20200720-010059

</details>

### CODE REVIEW

**Review by Skrilltrax — DISMISSED** [review]

**Comment by msfjarvis** [comment]
I'm not sure why emulator tests are failing here because they work fine on my local API 23 and API 29 emulators :/

**Comment by msfjarvis** [comment]
```
Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
(is displayed on the screen to the user and is assignable from class: class android.widget.EditText)
```

I have never seen this before

**Review by fmeum — DISMISSED** [review]

**Comment by fmeum** [comment]
Could we split off the item dividers? The custom font breaking our integration tests, but only in the CI, is so weird I don't have any idea of where to start fixing this.

**Comment by msfjarvis** [comment]
> Could we split off the item dividers? The custom font breaking our integration tests, but only in the CI, is so weird I don't have any idea of where to start fixing this.

Sure

**Pull request closed without merging**
